# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd_ipd_module', '0001_initial'),
        ('patient_module', '0001_initial'),
        ('setup_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipddischarge',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.bed'),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='patient_module.medicalcase'),
        ),
    ]
