# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd_ipd_module', '0002_initial'),
        ('pathology_module', '0002_initial'),
        ('patient_module', '0001_initial'),
        ('pharmacy_module', '0001_initial'),
        ('radiology_module', '0001_initial'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_patients_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom'),
        ),
        migrations.AddField(
            model_name='ipddischarge',
            name='ipd_patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='opd_ipd_module.ipdpatient'),
        ),
        migrations.AddField(
            model_name='nursenote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursenote',
            name='ipd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='opd_ipd_module.ipdpatient'),
        ),
        migrations.AddField(
            model_name='nursenote',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_visits', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='opd_patients_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom'),
        ),
        migrations.AddField(
            model_name='nursenote',
            name='opd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='opd_ipd_module.opdpatient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='findings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.finding'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ipd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='opd_ipd_module.ipdpatient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='opd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='opd_ipd_module.opdpatient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pathology',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='pathology_module.pathologytest'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='radiology',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='radiology_module.radiologytest'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.dosage'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinecategory'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine_dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinedosage'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='opd_ipd_module.prescription'),
        ),
    ]
