# Generated by Django 5.2.4 on 2026-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='payment_mode',
            field=models.CharField(blank=True, default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
