import IpdTableRow from "./IpdTableRow";

export default function IpdTable({ data }) {
  const headers = [
    { label: "Name", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Patient Id", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Case ID", class: "px-4 py-3 text-left whitespace-nowrap hidden lg:table-cell" },
    { label: "Gender", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Phone", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Generated By", class: "px-4 py-3 text-left whitespace-nowrap hidden md:table-cell" },
    { label: "Consultant Doctor", class: "px-4 py-3 text-left whitespace-nowrap hidden md:table-cell" },
    { label: "Admission Date", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Discharged Date", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Tax ($)", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Net Amount ($)", class: "px-4 py-3 text-left whitespace-nowrap" },
    { label: "Total ($)", class: "px-4 py-3 text-left whitespace-nowrap" },
  ];

  return (
    <div className="overflow-x-auto rounded-lg border">
      <table className="min-w-[1000px] w-full text-sm">
        <thead className="bg-gray-100 text-gray-700">
          <tr>
            {headers.map((h) => (
              <th key={h.label} className={h.class}>
                {h.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.length === 0 ? (
            <tr>
              <td colSpan={12} className="text-center py-6 text-gray-500">
                No records found
              </td>
            </tr>
          ) : (
            data.map((p, i) => <IpdTableRow key={i} p={p} />)
          )}
        </tbody>
      </table>
    </div>
  );
}
