import IpdTableRow from "./IpdTableRow";

export default function IpdTable({ data }) {
  return (
    <div className="overflow-x-auto rounded-lg border">
      <table className="min-w-[1400px] w-full text-sm">
        <thead className="bg-gray-100 text-gray-700">
          <tr>
            {[
              "Name",
              "Patient Id",
              "Case ID",
              "Gender",
              "Phone",
              "Generated By",
              "Consultant Doctor",
              "Admission Date",
              "Discharged Date",
              "Tax ($)",
              "Net Amount ($)",
              "Total ($)",
            ].map((h) => (
              <th key={h} className="px-4 py-3 text-left whitespace-nowrap">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.length === 0 ? (
            <tr>
              <td colSpan={12} className="text-center py-6 text-gray-500">
                No records found
              </td>
            </tr>
          ) : (
            data.map((p, i) => <IpdTableRow key={i} p={p} />)
          )}
        </tbody>
      </table>
    </div>
  );
}
