import DeathRecordRow from "./DeathRecordRow";

export default function DeathRecordTable({ records,onView,onEdit, onDelete }) {
  return (
    <div className="bg-white rounded shadow overflow-x-auto">
      <table className="min-w-full text-sm">
        <thead className="bg-gray-100 text-gray-700">
          <tr>
            <th className="px-3 py-2 text-left">Reference No</th>
            <th className="px-3 py-2">Case ID</th>
            <th className="px-3 py-2">Generated By</th>
            <th className="px-3 py-2">Patient</th>
            <th className="px-3 py-2">Guardian</th>
            <th className="px-3 py-2">Gender</th>
            <th className="px-3 py-2">Death Date</th>
            <th className="px-3 py-2">Report</th>
            <th className="px-3 py-2 text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          {records.map((item) => (
            <DeathRecordRow
              key={item.id}
              data={item}
              onDelete={onDelete}
              item={item}
              onView={onView}
               onEdit={onEdit}
            />
          ))}
        </tbody>
      </table>
    </div>
  );
}
