# Generated by Django 5.2.8 on 2026-01-02 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_adminprofile_merital_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='account_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='casual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='epf_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='fever_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='local_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='maternity_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='paternity_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='privilege_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='reference_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='merital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
