import { useEffect, useMemo, useRef, useState } from "react";
import AdminLayout from "../../layout/AdminLayout";
import { Plus, Trash2, Pencil } from "lucide-react";
import AddExpense from "../../components/Finance/AddExpense";
import UpdateExpense from "../../components/Finance/UpdateExpense";
import { getExpenses, deleteExpense } from "../../api/financeApi";
import { useNotify } from "../../context/NotificationContext";

export default function ExpenseList() {
  const notify = useNotify();

  // 🔹 Modal states (SEPARATED)
  const [addOpen, setAddOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [editId, setEditId] = useState(null);

  // 🔹 Data
  const [expenses, setExpenses] = useState([]);
  const [loading, setLoading] = useState(false);

  const searchRef = useRef("");
  const fetched = useRef(false);

  // 🔹 Fetch expenses (StrictMode safe)
  const fetchExpenses = async () => {
    setLoading(true);
    try {
      const res = await getExpenses();
      setExpenses(res.data);
    } catch {
      notify("error", "Failed to load expenses");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (fetched.current) return;
    fetched.current = true;
    fetchExpenses();
  }, []);

  // 🔹 Search
  const filteredExpenses = useMemo(() => {
    const q = searchRef.current.toLowerCase();
    if (!q) return expenses;

    return expenses.filter((item) =>
      [
        item.name,
        item.invoice_no,
        item.description,
        item.expense_head_name,
        item.created_by_name,
      ]
        .join(" ")
        .toLowerCase()
        .includes(q)
    );
  }, [expenses]);

  // 🔹 Delete
  const handleDelete = async (id) => {
    if (!confirm("Are you sure you want to delete this expense?")) return;

    try {
      await deleteExpense(id);
      notify("success", "Expense deleted successfully");
      fetchExpenses();
    } catch {
      notify("error", "Failed to delete expense");
    }
  };

  return (
    <AdminLayout>
      <div className="min-h-screen p-1">

        {/* HEADER */}
        <div className="flex flex-wrap justify-between items-center bg-white rounded-md p-3 shadow">
          <div>
            <h2 className="text-lg font-semibold pb-2">Expense List</h2>
            <input
              placeholder="Search..."
              onChange={(e) => {
                searchRef.current = e.target.value;
                setExpenses((prev) => [...prev]);
              }}
              className="border px-3 py-2 rounded text-sm w-full sm:w-64"
            />
          </div>

          <button
            onClick={() => setAddOpen(true)}
            className="flex items-center gap-2 bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
            text-white px-4 py-2 rounded-md"
          >
            <Plus size={16} /> Add Expense
          </button>
        </div>

        {/* TABLE */}
        <div className="bg-white rounded-md mt-4 overflow-x-auto shadow thin-scrollbar">
          <table className="w-full text-sm">
            <thead className="bg-gray-100">
              <tr>
                {[
                  "Name",
                  "Invoice No",
                  "Date",
                  "Description",
                  "Expense Head",
                  "Generated By",
                  "Amount ($)",
                  "Actions",
                ].map((h) => (
                  <th key={h} className="px-3 py-2 text-left">{h}</th>
                ))}
              </tr>
            </thead>

            <tbody>
              {loading && (
                <tr>
                  <td colSpan={8} className="p-4 text-center">Loading...</td>
                </tr>
              )}

              {!loading && filteredExpenses.length === 0 && (
                <tr>
                  <td colSpan={8} className="p-4 text-center text-gray-500">
                    No expense records found
                  </td>
                </tr>
              )}

              {filteredExpenses.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50">
                  <td className="px-3 py-2 text-blue-600">{item.name}</td>
                  <td className="px-3 py-2">{item.invoice_no || "-"}</td>
                  <td className="px-3 py-2">{item.date}</td>
                  <td className="px-3 py-2">{item.description || "-"}</td>
                  <td className="px-3 py-2">{item.expense_head_name}</td>
                  <td className="px-3 py-2">{item.created_by_name || "-"}</td>
                  <td className="px-3 py-2 font-medium">{item.amount}</td>
                  <td className="px-3 py-2 flex gap-2">
                    <button
                      onClick={() => {
                        setEditId(item.id);
                        setEditOpen(true);
                      }}
                      className="bg-green-100 p-2 rounded text-green-600 hover:bg-green-200"
                    >
                      <Pencil size={16} />
                    </button>
                    <button
                      onClick={() => handleDelete(item.id)}
                      className="bg-red-100 p-2 rounded text-red-600 hover:bg-red-200"
                    >
                      <Trash2 size={16} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* ADD MODAL */}
        <AddExpense
          open={addOpen}
          onClose={() => setAddOpen(false)}
          refresh={fetchExpenses}
        />

        {/* UPDATE MODAL */}
        <UpdateExpense
          open={editOpen}
          expenseId={editId}
          onClose={() => {
            setEditId(null);
            setEditOpen(false);
          }}
          refresh={fetchExpenses}
        />

      </div>
    </AdminLayout>
  );
}
