import { useState } from "react";
import AdminLayout from "../../layout/AdminLayout";
import { Plus } from "lucide-react";
import AddExpenseModal from "../../components/Finance/AddExpenseModal";

export default function ExpenseList() {
  const [openModal, setOpenModal] = useState(false);

  return (
    <AdminLayout>
      <div className="min-h-screen p-1 ">

        {/* HEADER */}
        <div className="flex flex-wrap justify-between items-center bg-white rounded-md p-3">
          <h2 className="text-lg font-semibold">Expense List</h2>

          <button
            onClick={() => setOpenModal(true)}
            className="flex items-center gap-2  bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-4 py-2 rounded-md"
          >
            <Plus size={16} /> Add Expense
          </button>
        </div>

        {/* TABLE */}
        <div className="bg-white rounded-md mt-4 overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-100">
              <tr>
                {[
                  "Name",
                  "Invoice Number",
                  "Date",
                  "Description",
                  "Expense Head",
                  "Generated By",
                  "Amount ($)",
                ].map((h) => (
                  <th key={h} className="px-3 py-2 text-left">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              <tr className="border-b hover:bg-gray-50">
                <td className="px-3 py-2 text-blue-600">Medical Equipment</td>
                <td className="px-3 py-2">IVN6522</td>
                <td className="px-3 py-2">01/02/2026</td>
                <td className="px-3 py-2">Medical Equipment</td>
                <td className="px-3 py-2">Equipments</td>
                <td className="px-3 py-2">Super Admin (9001)</td>
                <td className="px-3 py-2">120.00</td>
              </tr>

              <tr className="border-b hover:bg-gray-50">
                <td className="px-3 py-2 text-blue-600">Power Generator Charge</td>
                <td className="px-3 py-2">IVN4710</td>
                <td className="px-3 py-2">01/03/2026</td>
                <td className="px-3 py-2">Vehicle ownership cost</td>
                <td className="px-3 py-2">Fuel Charge</td>
                <td className="px-3 py-2">Super Admin (9001)</td>
                <td className="px-3 py-2">150.00</td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* MODAL */}
        <AddExpenseModal
          open={openModal}
          onClose={() => setOpenModal(false)}
        />

      </div>
    </AdminLayout>
  );
}
