import { useEffect, useMemo, useRef, useState } from "react";
import AdminLayout from "../../layout/AdminLayout";
import { Plus, Pencil, Trash2 } from "lucide-react";
import AddIncome from "../../components/Finance/AddIncome";
import { getIncomes, deleteIncome } from "../../api/financeApi";
import { useNotify } from "../../context/NotificationContext";
import UpdateIncome from "../../components/Finance/UpdateIncome";


export default function IncomeList() {
  const notify = useNotify();

  const [openModal, setOpenModal] = useState(false);
  const [incomes, setIncomes] = useState([]);
  const [loading, setLoading] = useState(false);
  const [editId, setEditId] = useState(null);

  const searchRef = useRef("");

  // 🔹 Fetch incomes
  const fetchIncomes = async () => {
    setLoading(true);
    try {
      const res = await getIncomes();
      setIncomes(res.data);
    } catch {
      notify( "error","Failed to load incomes");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchIncomes();
  }, []);

  // 🔹 Optimized search using useMemo
  const filteredIncomes = useMemo(() => {
    const q = searchRef.current.toLowerCase();

    if (!q) return incomes;

    return incomes.filter((item) =>
      [
        item.name,
        item.description,
        item.income_head_name,
        item.created_by_name,
      ]
        .join(" ")
        .toLowerCase()
        .includes(q)
    );
  }, [incomes, openModal]); // re-evaluate after add

  // 🔹 Delete income
  const handleDelete = async (id) => {
    if (!confirm("Are you sure you want to delete this income?")) return;

    try {
      await deleteIncome(id);
      notify( "success","Income deleted successfully");
      fetchIncomes();
    } catch {
      notify("error","Failed to delete income");
    }
  };

  return (
    <AdminLayout>
      <div className="min-h-screen p-1">

        {/* HEADER */}
        <div className="flex flex-wrap justify-between items-center bg-white rounded-md p-3 shadow">
          <div>
            <h1 className="text-xl font-semibold pb-4">Income List</h1>
            <input
              placeholder="Search..."
              onChange={(e) => {
                searchRef.current = e.target.value;
                setIncomes((prev) => [...prev]); // trigger memo
              }}
              className="border px-3 py-2 rounded text-sm w-full sm:w-64"
            />
          </div>

          <button
            onClick={() => setOpenModal(true)}
            className="flex items-center gap-2 bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-4 py-2 rounded-md"
          >
            <Plus size={16} /> Add Income
          </button>
        </div>

        {/* TABLE */}
        <div className="bg-white rounded-md mt-4 overflow-x-auto shadow">
          <table className="w-full text-sm">
            <thead className="bg-gray-100">
              <tr>
                {[
                  "Name",
                  "Invoice No",
                  "Date",
                  "Description",
                  "Income Head",
                  "Generated By",
                  "Amount ($)",
                  "Actions",
                ].map((h) => (
                  <th key={h} className="px-3 py-2 text-left">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {loading && (
                <tr>
                  <td colSpan={7} className="p-4 text-center">
                    Loading...
                  </td>
                </tr>
              )}

              {!loading && filteredIncomes.length === 0 && (
                <tr>
                  <td colSpan={7} className="p-4 text-center text-gray-500">
                    No income records found
                  </td>
                </tr>
              )}

              {filteredIncomes.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50">
                  <td className="px-3 py-2 text-blue-600">{item.name}</td>
                  <td className="px-3 py-2">{item.id || "-"}</td>
                  <td className="px-3 py-2">{item.date}</td>
                  <td className="px-3 py-2">
                    {item.description || "-"}
                  </td>
                  <td className="px-3 py-2">
                    {item.income_head_name}
                  </td>
                  <td className="px-3 py-2">
                    {item.created_by_name || "-"}
                  </td>
                  <td className="px-3 py-2 font-medium">
                    {item.amount}
                  </td>
                  <td className="p-3 flex gap-2">
                    <button
                      onClick={() => {
                        setEditId(item.id);
                        setOpenModal(true);
                      }}
                       className="bg-green-100 p-2 rounded text-green-600 hover:bg-green-200"
                    >
                      <Pencil size={16} />
                    </button>
                    <button
                      onClick={() => handleDelete(item.id)}
                      className="bg-red-100 p-2 rounded text-red-600 hover:bg-red-200"
                    >
                      <Trash2 size={16} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* ADD MODAL */}
        <AddIncome
          open={openModal}
          onClose={() => setOpenModal(false)}
          refresh={fetchIncomes}
        />
        <UpdateIncome
          open={openModal}
          incomeId={editId}
          onClose={() => {
            setEditId(null);
            setOpenModal(false);
          }}
          refresh={fetchIncomes}
        />

      </div>
    </AdminLayout>
  );
}
