import { useEffect, useMemo, useRef, useState } from "react";
import AdminLayout from "../../layout/AdminLayout";
import { Plus, Pencil, Trash2 } from "lucide-react";
import AddIncome from "../../components/Finance/AddIncome";
import UpdateIncome from "../../components/Finance/UpdateIncome";
import { getIncomes, deleteIncome } from "../../api/financeApi";
import { useNotify } from "../../context/NotificationContext";

export default function IncomeList() {
  const notify = useNotify();

  // 🔹 Modal states (SEPARATED)
  const [addOpen, setAddOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [editId, setEditId] = useState(null);

  // 🔹 Data states
  const [incomes, setIncomes] = useState([]);
  const [loading, setLoading] = useState(false);

  // 🔹 Utils
  const searchRef = useRef("");
  const hasFetched = useRef(false);

  // 🔹 Fetch incomes (STRICTMODE SAFE)
  const fetchIncomes = async () => {
    setLoading(true);
    try {
      const res = await getIncomes();
      setIncomes(res.data);
    } catch {
      notify("error", "Failed to load incomes");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (hasFetched.current) return;
    hasFetched.current = true;
    fetchIncomes();
  }, []);

  // 🔹 Search filter
  const filteredIncomes = useMemo(() => {
    const q = searchRef.current.toLowerCase();
    if (!q) return incomes;

    return incomes.filter((item) =>
      [
        item.name,
        item.description,
        item.income_head_name,
        item.created_by_name,
      ]
        .join(" ")
        .toLowerCase()
        .includes(q)
    );
  }, [incomes]);

  // 🔹 Delete income
  const handleDelete = async (id) => {
    if (!confirm("Are you sure you want to delete this income?")) return;

    try {
      await deleteIncome(id);
      notify("success", "Income deleted successfully");
      fetchIncomes();
    } catch {
      notify("error", "Failed to delete income");
    }
  };

  return (
    <AdminLayout>
      <div className="min-h-screen p-1">

        {/* HEADER */}
        <div className="flex flex-wrap justify-between items-center bg-white rounded-md p-3 shadow">
          <div>
            <h1 className="text-xl font-semibold pb-3">Income List</h1>
            <input
              placeholder="Search..."
              onChange={(e) => {
                searchRef.current = e.target.value;
                setIncomes((prev) => [...prev]); // trigger memo
              }}
             className="w-full mt-1 border border-gray-300 focus:border-[#6046B5] focus:ring-0.5 focus:ring-[#8A63D2] outline-none transition rounded px-3 py-2"
            />
          </div>

          <button
            onClick={() => setAddOpen(true)}
            className="flex items-center gap-2 bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
            text-white px-4 py-2 rounded-md"
          >
            <Plus size={16} /> Add Income
          </button>
        </div>

        {/* TABLE */}
        <div className="bg-white rounded-md mt-4 overflow-x-auto shadow thin-scrollbar">
          <table className="w-full text-sm">
            <thead className="bg-gray-100">
              <tr>
                {[
                  "Name",
                  "Invoice No",
                  "Date",
                  "Description",
                  "Income Head",
                  "Generated By",
                  "Amount ($)",
                  "Actions",
                ].map((h) => (
                  <th key={h} className="px-3 py-2 text-left">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {loading && (
                <tr>
                  <td colSpan={8} className="p-4 text-center">
                    Loading...
                  </td>
                </tr>
              )}

              {!loading && filteredIncomes.length === 0 && (
                <tr>
                  <td colSpan={8} className="p-4 text-center text-gray-500">
                    No income records found
                  </td>
                </tr>
              )}

              {filteredIncomes.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50 border-b border-gray-200">
                  <td className="px-3 py-2 text-blue-600">{item.name}</td>
                  <td className="px-3 py-2">{item.id}</td>
                  <td className="px-3 py-2">{item.date}</td>
                  <td className="px-3 py-2">{item.description || "-"}</td>
                  <td className="px-3 py-2">{item.income_head_name}</td>
                  <td className="px-3 py-2">{item.created_by_name || "-"}</td>
                  <td className="px-3 py-2 font-medium">{item.amount}</td>
                  <td className="px-3 py-2 flex gap-2">
                    <button
                      onClick={() => {
                        setEditId(item.id);
                        setEditOpen(true);
                      }}
                      className="p-1 rounded text-green-600 hover:bg-green-100"
                    >
                      <Pencil size={16} />
                    </button>
                    <button
                      onClick={() => handleDelete(item.id)}
                      className="p-1 rounded text-red-600 hover:bg-red-100"
                    >
                      <Trash2 size={16} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* ADD MODAL */}
        <AddIncome
          open={addOpen}
          onClose={() => setAddOpen(false)}
          refresh={fetchIncomes}
        />

        {/* UPDATE MODAL */}
        <UpdateIncome
          open={editOpen}
          incomeId={editId}
          onClose={() => {
            setEditId(null);
            setEditOpen(false);
          }}
          refresh={fetchIncomes}
        />

      </div>
    </AdminLayout>
  );
}
