# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('slot', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='setup_module.hospitalcharges')),
            ],
        ),
    ]
