import React, { useState } from "react";
import Sidebar from "../../components/CommonComponent/Sidebar";
import Navbar from "../../components/AdminComponent/Navbar";
import { useNavigate } from "react-router-dom";
import {
  Plus,
  FileText,
  FileSpreadsheet,
  Printer,
  File,
} from "lucide-react";

const ipdPatients = [
  {
    ipdNo: "IPDN115",
    caseId: "7577",
    name: "rodrigoues mathew (1164)",
    gender: "Male",
    phone: "99999947279",
    generatedBy: "Super Admin (9001)",
    consultant: "Reyan Jain (9011)",
    bed: "GF - 109-VIP Ward-Ground Floor",
    antenatal: "No",
    medicalIssue: "appendectomy",
    credit: "10000.00",
  },
  {
    ipdNo: "IPDN113",
    caseId: "7490",
    name: "Rachel Priest (1162)",
    gender: "Female",
    phone: "90980678776",
    generatedBy: "Super Admin (9001)",
    consultant: "Sonia Bush (9002)",
    bed: "TF - 104-Private Ward-3rd Floor",
    antenatal: "No",
    medicalIssue: "NA",
    credit: "20000.00",
  },
];

export default function IpdPatient() {
  const [search, setSearch] = useState("");
  const [limit, setLimit] = useState(100);
  const navigate = useNavigate();
  return (
    <div className="h-screen w-screen flex bg-gray-100 overflow-hidden">
      <Sidebar />

      <div className="flex flex-col flex-1 overflow-hidden">
        <Navbar />

        <main className="flex-1 overflow-y-auto p-4 md:p-6">
          <div className="bg-white rounded-lg shadow border border-gray-200 p-4 md:p-6">

            {/* HEADER */}
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
              <h2 className="text-lg font-semibold">IPD Patient</h2>

              <div className="flex gap-2 flex-col sm:flex-row">
                <button
                  className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
                             text-white px-4 py-2 rounded flex items-center gap-2 justify-center"
                              onClick={() => navigate('/admin/ipd-patients/add-ipd')}
                >
                  <Plus size={16} /> Add Patient
                   
                </button>

                <button   
                  onClick={() => navigate('/admin/ipd-patients/ipd-discharged-patients')}
                  className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
                             text-white px-4 py-2 rounded flex items-center gap-2 justify-center"
                >
                  Discharged Patient
                </button>
              </div>
            </div>

            {/* SEARCH + ACTIONS */}
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
              <input
                type="text"
                placeholder="Search..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="border px-3 py-2 rounded w-full lg:w-64"
              />

              <div className="flex flex-wrap gap-3 items-center justify-between lg:justify-end">
                <select
                  value={limit}
                  onChange={(e) => setLimit(e.target.value)}
                  className="border px-2 py-2 rounded text-sm"
                >
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>

                <div className="flex gap-2">
                  <FileText size={18} className="cursor-pointer text-gray-600" />
                  <FileSpreadsheet size={18} className="cursor-pointer text-gray-600" />
                  <File size={18} className="cursor-pointer text-gray-600" />
                  <Printer size={18} className="cursor-pointer text-gray-600" />
                </div>
              </div>
            </div>

            {/* TABLE */}
            <div className="overflow-x-auto">
              <table className="min-w-[1400px] w-full text-sm border-separate border-spacing-0">
                <thead className="bg-gray-50 border-y">
                  <tr>
                    <th className="px-4 py-2 text-left">IPD No</th>
                    <th className="px-4 py-2 text-left">Case ID</th>
                    <th className="px-4 py-2 text-left">Name</th>
                    <th className="px-4 py-2 text-left">Gender</th>
                    <th className="px-4 py-2 text-left">Phone</th>
                    <th className="px-4 py-2 text-left">Generated By</th>
                    <th className="px-4 py-2 text-left">Consultant Doctor</th>
                    <th className="px-4 py-2 text-left">Bed</th>
                    <th className="px-4 py-2 text-left">Is Antenatal</th>
                    <th className="px-4 py-2 text-left">Previous Medical Issue</th>
                    <th className="px-4 py-2 text-right">Credit Limit ($)</th>
                  </tr>
                </thead>

                <tbody className="divide-y divide-gray-200">
                  {ipdPatients.map((p, i) => (
                    <tr key={i} className="hover:bg-gray-50">
                      <td className="px-4 py-3 text-blue-600 cursor-pointer">
                        {p.ipdNo}
                      </td>
                      <td className="px-4 py-3">{p.caseId}</td>
                      <td className="px-4 py-3">{p.name}</td>
                      <td className="px-4 py-3">{p.gender}</td>
                      <td className="px-4 py-3">{p.phone}</td>
                      <td className="px-4 py-3">{p.generatedBy}</td>
                      <td className="px-4 py-3">{p.consultant}</td>
                      <td className="px-4 py-3">{p.bed}</td>
                      <td className="px-4 py-3">{p.antenatal}</td>
                      <td className="px-4 py-3">{p.medicalIssue}</td>
                      <td className="px-4 py-3 text-right">
                        {p.credit}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* FOOTER */}
            <div className="flex justify-between items-center mt-4 text-sm text-gray-500">
              <span>Records: 1 to {ipdPatients.length} of {ipdPatients.length}</span>
              <div className="flex gap-2">
                <button className="px-2">‹</button>
                <button className="px-2">›</button>
              </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
}
