# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_module', '0002_initial'),
        ('pharmacy_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy_module.medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='pharmacy_module.medicinecategory'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_doases', to='pharmacy_module.medicinecategory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinegroup'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacy_module.medicinebatch'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_module.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='pharmacybillitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.medicinebatch'),
        ),
        migrations.AddField(
            model_name='pharmacybillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_module.pharmacybill'),
        ),
        migrations.AddField(
            model_name='pharmacybillitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.medicinebatch'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_module.pharmacypurchase'),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.supplier'),
        ),
        migrations.AddField(
            model_name='medicinedosage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_dosages', to='pharmacy_module.unit'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('medicine', 'batch_no')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinestock',
            unique_together={('medicine', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinedosage',
            unique_together={('category_name', 'dosage', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('name', 'company')},
        ),
    ]
