import React, { useState } from "react";
import { Plus, List, Eye, Pencil, Trash2, Printer } from "lucide-react";
import { useNavigate } from "react-router-dom";
import AdminLayout from "../../layout/AdminLayout";
import useAmbulanceCalls from "../../hooks/useAmbulanceCalls";
import GenerateAmbulanceBill from "../../components/Ambulance/GenerateAmbulanceBill";
import UpdateAmbulance from "../../components/Ambulance/UpdateAmbulance";
import AmbulanceBillDetail from "../../components/Ambulance/AmbulanceBillDetail";
import { deleteAmbulanceBill } from "../../api/ambulanceApi";
import { useNotify } from "../../context/NotificationContext";

export default function AmbulanceCallList() {
  const navigate = useNavigate();
  const notify = useNotify();
  const { search, setSearch, data, loading, refresh } = useAmbulanceCalls();
  const [open, setOpen] = useState(false);
  const [viewBillId, setViewBillId] = useState(null);
  const [editBillId, setEditBillId] = useState(null);
  const [openUpdate, setOpenUpdate] = useState(false);

  const handleDelete = async (billId) => {
    if (!window.confirm("Are you sure you want to delete this ambulance bill?")) {
      return;
    }

    try {
      await deleteAmbulanceBill(billId);
      notify("success", "Ambulance bill deleted successfully");
      refresh(); // Refresh the list
    } catch (error) {
      notify("error", error?.response?.data?.message || "Failed to delete ambulance bill");
    }
  };

  return (
    <AdminLayout>
      {/* PAGE CONTAINER */}
      <div className="w-full rounded-lg bg-white  md:p-4 shadow-md">

        {/* HEADER SECTION */}
        <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">

          {/* TITLE + SEARCH */}
          <div className="flex-1">
            <h2 className="text-xl md:text-2xl font-semibold text-gray-800 mb-4">
              Ambulance Call List
            </h2>

            <div className="relative w-full sm:w-80">
              <input
                type="text"
                placeholder="Search by Bill No or Patient"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full px-4 py-2.5 rounded-md text-sm outline-none border border-gray-300 focus:ring-2 focus:ring-purple-600 focus:border-purple-600"
              />
            </div>
          </div>

          {/* ACTION BUTTONS */}
          <div className="flex flex-wrap gap-3 items-start">
            <button
              onClick={() => setOpen(true)}
              className="flex items-center gap-2 bg-gradient-to-r from-[#6046B5] to-[#8A63D2] text-white px-5 py-2.5 rounded-md text-sm font-medium shadow-md hover:shadow-lg transition-shadow"
            >
              <Plus size={18} />
              Add Ambulance Bill
            </button>

            <button
              onClick={() => navigate("/admin/ambulance-list")}
              className="flex items-center gap-2 bg-gradient-to-r from-[#6046B5] to-[#8A63D2] text-white px-5 py-2.5 rounded-md text-sm font-medium shadow-md hover:shadow-lg transition-shadow"
            >
              <List size={18} />
              Ambulance List
            </button>
          </div>
        </div>

        {/* TABLE */}
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm mt-6 overflow-x-auto lg:overflow-x-visible">
          <table className="w-full text-left table-auto min-w-[900px] lg:min-w-0">
            <thead className="bg-gradient-to-r from-gray-50 to-gray-100 border-b-2 border-gray-200">
              <tr>
                {[
                  "Bill No",
                  "Case ID",
                  "Patient",
                  "Generated By",
                  "Vehicle No",
                  "Model",
                  "Driver",
                  "Contact",
                  "Address",
                  "Date",
                  "Amount",
                  "Net",
                  "Paid",
                  "Balance",
                  "Actions",
                ].map((h) => (
                  <th key={h} className="px-2 py-3 text-sm font-bold text-gray-700 whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="17" className="text-center py-6 text-gray-500">
                    Loading...
                  </td>
                </tr>
              ) : data.length === 0 ? (
                <tr>
                  <td colSpan="17" className="text-center py-6 text-gray-500">
                    No Records Found
                  </td>
                </tr>
              ) : (
                data.map((row, i) => (
                  <tr
                    key={i}
                    className="border-b border-gray-200 text-sm hover:bg-purple-50 transition-colors"
                  >
                    <td className="px-2 py-3 ">{row.billNo}</td>
                    <td className="px-2 py-3 ">{row.caseId}</td>
                    <td className="px-2 py-3 ">{row.patient}</td>
                    <td className="px-2 py-3 ">{row.generatedBy}</td>
                    <td className="px-2 py-3 ">{row.vehicleNo}</td>
                    <td className="px-2 py-3 ">{row.model}</td>
                    <td className="px-2 py-3 ">{row.driver}</td>
                    <td className="px-2 py-3 ">{row.contact}</td>
                    <td className="px-2 py-3  ">{row.address}</td>
                    <td className="px-2 py-3 ">{row.date}</td>
                    <td className="px-2 py-3 ">${row.amount.toFixed(2)}</td>
                    <td className="px-2 py-3  ">${row.net.toFixed(2)}</td>
                    <td className="px-2 py-3  ">${row.paid.toFixed(2)}</td>
                    <td className="px-2 py-3  ">${row.balance.toFixed(2)}</td>

                    {/* ACTIONS */}
                    <td className="px-2 py-3">
                      <div className="flex items-center gap-2">
                        <button
                          title="View"
                          onClick={() => {
                            if (row.id) {
                              setViewBillId(row.id);
                            } else {
                              console.error("Cannot view bill: row.id is undefined", row);
                            }
                          }}
                          disabled={!row.id}
                          className="p-1 rounded hover:bg-purple-100 text-purple-600 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          <Eye size={16} />
                        </button>

                        <button
                          title="Edit"
                          onClick={() => {
                            if (row.id) {
                              setEditBillId(row.id);
                              setOpenUpdate(true);
                            } else {
                              console.error("Cannot edit bill: row.id is undefined", row);
                            }
                          }}
                          disabled={!row.id}
                          className="p-1 rounded hover:bg-green-100 text-green-600 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          <Pencil size={16} />
                        </button>

                        <button
                          title="Delete"
                          onClick={() => {
                            if (row.id) {
                              handleDelete(row.id);
                            } else {
                              console.error("Cannot delete bill: row.id is undefined", row);
                            }
                          }}
                          disabled={!row.id}
                          className="p-1 rounded hover:bg-red-100 text-red-600 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ADD AMBULANCE MODAL */}
      <GenerateAmbulanceBill
        open={open}
        onClose={() => setOpen(false)}
        onSuccess={refresh}
      />

      {/* UPDATE AMBULANCE BILL MODAL */}
      <UpdateAmbulance
        open={openUpdate}
        onClose={() => {
          setOpenUpdate(false);
          setEditBillId(null);
        }}
        billId={editBillId}
        onSuccess={() => {
          refresh();
          setOpenUpdate(false);
          setEditBillId(null);
        }}
      />

      {/* AMBULANCE BILL DETAIL MODAL */}
      <AmbulanceBillDetail
        open={viewBillId !== null}
        billId={viewBillId}
        onClose={() => setViewBillId(null)}
      />
    </AdminLayout>
  );
}
