import { useState, useEffect } from "react";
import { Eye, Pencil, Trash2 } from "lucide-react";
import AdminLayout from "../../layout/AdminLayout";
import useBirthRecords from "../../hooks/useBirthRecords";
import AddBirthRecord from "../../components/BirthDeathrecord/AddBirthRecord";
import BirthRecordDetails from "../../components/BirthDeathrecord/BirthRecordDetails";
import UpdateBirthRecord from "../../components/BirthDeathrecord/UpdateBirthRecord";
import { deleteBirthRecord } from "../../api/birthDeathApi";
import { useNotify } from "../../context/NotificationContext";

export default function BirthRecord() {
  const { search, setSearch, data, refresh } = useBirthRecords();
  const notify = useNotify();

  const [openAdd, setOpenAdd] = useState(false);
  const [openDetails, setOpenDetails] = useState(false);
  const [openEdit, setOpenEdit] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);
  const [records, setRecords] = useState(data || []);

  // Sync API data
  useEffect(() => {
    if (data) setRecords(data);
  }, [data]);

  /* ================== ACTION HANDLERS ================== */

  const handleView = (record) => {
    setSelectedRecord(record);
    setOpenDetails(true);
  };

  const handleEdit = (record) => {
    setSelectedRecord(record);
    setOpenEdit(true);
  };

  const handleSave = (updated) => {
    // Update is handled in UpdateBirthRecord component
    refresh();
    setOpenEdit(false);
  };

  const handleDelete = async (record) => {
    if (!record?.id) return;
    const confirmDelete = window.confirm("Are you sure you want to delete this birth record?");
    if (!confirmDelete) return;

    try {
      await deleteBirthRecord(record.id);
      notify("success", "Birth record deleted successfully");
      refresh();
    } catch (error) {
      const errorMsg = error?.response?.data?.error || error?.message || "Failed to delete birth record";
      notify("error", errorMsg);
    }
  };

  return (
    <AdminLayout>
      <div className="min-h-full p-1">
        <div className="bg-white rounded shadow p-4 max-w-8xl mx-auto">

          {/* HEADER */}
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4">
            <div>
              <h1 className="text-xl font-semibold pb-4">Birth Record</h1>
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search..."
                className="w-full border border-gray-300 focus:border-[#6046B5] focus:ring-0.5 focus:ring-[#8A63D2] outline-none transition rounded px-3 py-1"
              />
            </div>

            <div className="flex flex-col sm:flex-row gap-3">


              <button
                onClick={() => setOpenAdd(true)}
                className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-4 py-2 rounded text-sm"
              >
                + Add Birth Record
              </button>
            </div>
          </div>

          {/* TABLE */}
          <div className="overflow-x-auto thin-scrollbar">
            <table className="min-w-full text-left bg-white">
              <thead className="bg-gray-100 text-sm">
                <tr>
                  <th className="px-3 py-2">Reference No</th>
                  <th className="px-3 py-2">Case ID</th>
                  <th className="px-3 py-2">Generated By</th>
                  <th className="px-3 py-2">Child Name</th>
                  <th className="px-3 py-2">Gender</th>
                  <th className="px-3 py-2">Birth Date</th>
                  <th className="px-3 py-2">Mother Name</th>
                  <th className="px-3 py-2">Father Name</th>
                  <th className="px-3 py-2">Report</th>
                </tr>
              </thead>

              <tbody>
                {records.map((item, i) => (
                  <tr key={i} className=" text-sm group hover:bg-gray-50 transition border-b border-gray-200">
                    <td className="px-3 py-2">{item.id}</td>
                    <td className="px-3 py-2">{item.caseId}</td>
                    <td className="px-3 py-2">{item.generatedBy}</td>
                    <td className="px-3 py-2">{item.childName}</td>
                    <td className="px-3 py-2">{item.gender}</td>
                    <td className="px-3 py-2 whitespace-nowrap">{item.birthDate}</td>
                    <td className="px-3 py-2">{item.motherName}</td>
                    <td className="px-3 py-2">{item.fatherName}</td>

                    {/* ACTIONS */}
                    <td className="px-3 py-2">
                      <div className="flex gap-1">
                        <button className="p-1 rounded text-purple-600 hover:bg-purple-100"
                          onClick={() => handleView(item)}
                        >
                          <Eye size={16}/>
                        </button>
                        <button className="p-1 rounded text-green-600 hover:bg-green-100"
                          onClick={() => handleEdit(item)}
                        >
                          <Pencil size={16}/>
                        </button>
                        <button className="p-1 rounded text-red-600 hover:bg-red-100"
                          onClick={() => handleDelete(item)}
                       >
                        <Trash2 size={16}/>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* MODALS */}
          <AddBirthRecord
            open={openAdd}
            onClose={() => setOpenAdd(false)}
            onSuccess={() => {
              refresh();
              setOpenAdd(false);
            }}
          />

          <BirthRecordDetails
            open={openDetails}
            onClose={() => setOpenDetails(false)}
            record={selectedRecord || {}}
            onEdit={(rec) => {
              setOpenDetails(false);
              handleEdit(rec);
            }}
            onDelete={(rec) => {
              setOpenDetails(false);
              handleDelete(rec);
            }}
          />

          <UpdateBirthRecord
            open={openEdit}
            onClose={() => setOpenEdit(false)}
            record={selectedRecord}
            onSave={handleSave}
          />

        </div>
      </div>
    </AdminLayout>
  );
}
