import { useState } from "react";
import { Eye, Pencil, Trash2 } from "lucide-react";
import AdminLayout from "../../layout/AdminLayout";
import useBirthRecords from "../../hooks/useBirthRecords";
import AddBirthRecord from "../../components/BirthDeathrecord/AddBirthRecord";
import BirthRecordDetails from "../../components/BirthDeathrecord/BirthRecordDetails";
import UpdateBirthRecord from "../../components/BirthDeathrecord/UpdateBirthRecord";

export default function BirthRecord() {
  const { search, setSearch, data } = useBirthRecords();

  const [openAdd, setOpenAdd] = useState(false);
  const [openDetails, setOpenDetails] = useState(false);
  const [openEdit, setOpenEdit] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);
  const [records, setRecords] = useState(data || []);

  // Sync API data
  useState(() => {
    if (data) setRecords(data);
  }, [data]);

  /* ================== ACTION HANDLERS ================== */

  const handleView = (record) => {
    setSelectedRecord(record);
    setOpenDetails(true);
  };

  const handleEdit = (record) => {
    setSelectedRecord(record);
    setOpenEdit(true);
  };

  const handleSave = (updated) => {
    console.log("UPDATE API CALL", updated);
    setOpenEdit(false);
  };

  const handleDelete = (record) => {
    if (!record?.id) return;
    const confirmDelete = window.confirm("Are you sure you want to delete this birth record?");
    if (!confirmDelete) return;

    console.log("Deleting record:", record);
    setRecords((prev) => prev.filter((i) => i.id !== record.id));
  };

  return (
    <AdminLayout>
      <div className="min-h-full p-1">
        <div className="bg-white rounded shadow p-4 max-w-7xl mx-auto">

          {/* HEADER */}
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4">
            <div>
            <h1 className="text-xl font-semibold pb-4">Birth Record</h1>
            <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search..."
                className="border px-3 py-2 rounded text-sm w-full sm:w-64"
              />
            </div>

            <div className="flex flex-col sm:flex-row gap-3">
              

              <button
                onClick={() => setOpenAdd(true)}
                className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-4 py-2 rounded text-sm"
              >
                + Add Birth Record
              </button>
            </div>
          </div>

          {/* TABLE */}
          <div className="overflow-x-auto">
            <table className="min-w-full text-left bg-white">
              <thead className="bg-gray-100 text-sm">
                <tr>
                  <th className="px-3 py-2">Reference No</th>
                  <th className="px-3 py-2">Case ID</th>
                  <th className="px-3 py-2">Generated By</th>
                  <th className="px-3 py-2">Child Name</th>
                  <th className="px-3 py-2">Gender</th>
                  <th className="px-3 py-2">Birth Date</th>
                  <th className="px-3 py-2">Mother Name</th>
                  <th className="px-3 py-2">Father Name</th>
                  <th className="px-3 py-2">Report</th>
                </tr>
              </thead>

              <tbody>
                {records.map((item, i) => (
                  <tr key={i} className=" text-sm group hover:bg-gray-50 transition">
                    <td className="px-3 py-2">{item.refNo}</td>
                    <td className="px-3 py-2">{item.caseId}</td>
                    <td className="px-3 py-2">{item.generatedBy}</td>
                    <td className="px-3 py-2">{item.childName}</td>
                    <td className="px-3 py-2">{item.gender}</td>
                    <td className="px-3 py-2 whitespace-nowrap">{item.birthDate}</td>
                    <td className="px-3 py-2">{item.mother}</td>
                    <td className="px-3 py-2">{item.father}</td>

                    {/* ACTIONS */}
                    <td className="px-3 py-2">
                      <div className="flex gap-3">
                        <Eye
                          className="w-4 h-4 text-blue-600 cursor-pointer"
                          onClick={() => handleView(item)}
                        />
                        <Pencil
                          className="w-4 h-4 text-green-600 cursor-pointer"
                          onClick={() => handleEdit(item)}
                        />
                        <Trash2
                          className="w-4 h-4 text-red-600 cursor-pointer"
                          onClick={() => handleDelete(item)}
                        />
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* MODALS */}
          <AddBirthRecord open={openAdd} onClose={() => setOpenAdd(false)} />

          <BirthRecordDetails
            open={openDetails}
            onClose={() => setOpenDetails(false)}
            record={selectedRecord || {}}
          />

          <UpdateBirthRecord
            open={openEdit}
            onClose={() => setOpenEdit(false)}
            record={selectedRecord}
            onSave={handleSave}
          />

        </div>
      </div>
    </AdminLayout>
  );
}
