import { useState, useEffect } from "react";
import { Eye, Pencil, Trash2, Plus } from "lucide-react";
import AdminLayout from "../../layout/AdminLayout";
import useDeathRecords from "../../hooks/useDeathRecords";
import AddDeathRecord from "../../components/BirthDeathrecord/AddDeathRecord";
import DeathRecordDetails from "../../components/BirthDeathrecord/DeathRecordDetails";
import UpdateDeathRecord from "../../components/BirthDeathrecord/UpdateDeathRecord";

export default function DeathRecordPage() {
  const { records, search, setSearch, deleteRecord, refresh } = useDeathRecords();

  const [data, setData] = useState([]);
  const [openAdd, setOpenAdd] = useState(false);
  const [openDetails, setOpenDetails] = useState(false);
  const [openEdit, setOpenEdit] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);

  useEffect(() => {
    if (records) setData(records);
  }, [records]);

  /* =================== HANDLERS =================== */

  const handleView = (record) => {
    setSelectedRecord(record);
    setOpenDetails(true);
  };

  const handleEdit = (record) => {
    setSelectedRecord(record);
    setOpenEdit(true);
  };

  const handleSave = (updatedData) => {
    console.log("UPDATE DEATH RECORD API", updatedData);
    setOpenEdit(false);
  };

  const handleDelete = (record) => {
    if (!window.confirm("Delete this death record?")) return;
    deleteRecord(record.id);
  };

  /* =================== UI =================== */

  return (
    <AdminLayout>
      <div className="min-h-full p-1">
        <div className="max-w-8xl mx-auto">

          {/* HEADER */}
          <div className="flex flex-col md:flex-row md:items-center md:justify-between bg-white gap-3 p-4">
            <div>
              <h2 className="text-black text-xl font-semibold pb-4">Death Record</h2>
             <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search..."
                className="border px-3 py-2 rounded text-sm w-full sm:w-64"
              />
            </div>
            <div className="flex gap-2 w-full md:w-auto">
              <button
                onClick={() => setOpenAdd(true)}
                className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-3 py-2 rounded flex items-center gap-1 text-sm"
              >
                <Plus size={16} /> Add Death Record
              </button>
            </div>
          </div>

          {/* TABLE */}
          <div className="bg-white rounded shadow overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead className="bg-gray-100 text-gray-700">
                <tr>
                  <th className="px-3 py-2 text-left">Reference No</th>
                  <th className="px-3 py-2 text-left">Case ID</th>
                  <th className="px-3 py-2 text-left">Generated By</th>
                  <th className="px-3 py-2 text-left">Patient</th>
                  <th className="px-3 py-2 text-left">Guardian</th>
                  <th className="px-3 py-2 text-left">Gender</th>
                  <th className="px-3 py-2 text-left">Death Date</th>
                  <th className="px-3 py-2 text-left">Report</th>
                  <th className="px-3 py-2 text-left">Action</th>
                </tr>
              </thead>

              <tbody>
                {data.map((item) => (
                  <tr key={item.id} className="border-b border-gray-200 group hover:bg-gray-50 transition">
                    <td className="px-3 py-2">{item.id}</td>
                    <td className="px-3 py-2 text-center">{item.caseId}</td>
                    <td className="px-3 py-2">{item.generatedBy}</td>
                    <td className="px-3 py-2">{item.patient}</td>
                    <td className="px-3 py-2">{item.guardian}</td>
                    <td className="px-3 py-2">{item.gender}</td>
                    <td className="px-3 py-2">{item.date}</td>
                    <td className="px-3 py-2">{item.report}</td>

                    {/* ACTIONS */}
                    <td className="px-3 py-2">
                      <div className="flex  gap-2">
                        <button
                          onClick={() => handleView(item)}
                          className="p-1 bg-blue-100 text-blue-600 rounded hover:bg-blue-200"
                        >
                          <Eye size={16} />
                        </button>

                        <button
                          onClick={() => handleEdit(item)}
                          className="p-1 bg-green-100 text-green-600 rounded hover:bg-green-200"
                        >
                          <Pencil size={16} />
                        </button>

                        <button
                          onClick={() => handleDelete(item)}
                          className="p-1 bg-red-100 text-red-600 rounded hover:bg-red-200"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* MODALS */}
          <AddDeathRecord 
            open={openAdd} 
            onClose={() => setOpenAdd(false)}
            onSuccess={() => {
              refresh();
              setOpenAdd(false);
            }}
          />

          <DeathRecordDetails
            open={openDetails}
            onClose={() => setOpenDetails(false)}
            record={selectedRecord}
          />

          <UpdateDeathRecord
            open={openEdit}
            onClose={() => setOpenEdit(false)}
            record={selectedRecord}
            onSave={handleSave}
          />

        </div>
      </div>
    </AdminLayout>
  );
}
