# Generated by Django 5.2.8 on 2026-01-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birth_death_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthrecord',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='reference_no',
        ),
    ]
