# Generated by Django 5.2.8 on 2026-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateTimeField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('child_photo', models.ImageField(blank=True, null=True, upload_to='birth_records/child_photos/')),
                ('mother_photo', models.ImageField(blank=True, null=True, upload_to='birth_records/mother_photos/')),
                ('father_photo', models.ImageField(blank=True, null=True, upload_to='birth_records/father_photos/')),
                ('document_photo', models.ImageField(blank=True, null=True, upload_to='birth_records/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('death_date', models.DateField()),
                ('guardian_name', models.CharField(blank=True, max_length=150, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='death_records/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
