import React, { useState } from "react";
import Sidebar from "../../components/CommonComponent/Sidebar";
import Navbar from "../../components/AdminComponent/Navbar";
import { useNavigate } from "react-router-dom";
import {Plus,FileText,FileSpreadsheet,Printer,File,} from "lucide-react";
import { getOpdPatientList } from "../../api/opdApi";
import { useEffect } from "react";

const tabs = [
  { label: "Today OPD", value: "today" },
  { label: "Upcoming OPD", value: "upcoming" },
  { label: "Old OPD", value: "old" },
  { label: "Patient View", value: "patient" },
];


export default function OpdPatient() {
  const navigate = useNavigate();
 const [activeTab, setActiveTab] = useState("today");
  const [search, setSearch] = useState("");
  const [limit, setLimit] = useState(100);
  const [opdList, setOpdList] = useState([]);
  const [loading, setLoading] = useState(false);

useEffect(() => {
    fetchOpd();
  }, [activeTab]);

  const fetchOpd = async () => {
    try {
      setLoading(true);
      const res = await getOpdPatientList(activeTab);
      setOpdList(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };


  return (
    <div className="h-screen w-screen flex bg-gray-100 overflow-hidden">
      <Sidebar />

      <div className="flex flex-col flex-1 overflow-hidden">
        <Navbar />

        <main className="flex-1 overflow-y-auto p-4 md:p-6">
          <div className="bg-white rounded-lg shadow border border-gray-200 p-4 md:p-6">

            {/* TABS + ADD BUTTON */}
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
              {/* Tabs */}
             <div className="flex flex-wrap gap-6 text-sm font-medium">
              {tabs.map((tab) => (
              <button
                key={tab.value}
                onClick={() => setActiveTab(tab.value)}
                className={`pb-2 transition-colors duration-200 ${
                  activeTab === tab.value
                    ? "text-[#6046B5] border-b-2 border-[#6046B5] font-semibold"
                    : "text-gray-600 hover:text-[#6046B5]"
                }`}
              >
                {tab.label}
              </button>
            ))}

            </div>
              {/* Add Patient */}
              <button
                className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
                            text-white px-4 py-2 rounded
                            flex items-center gap-2
                            w-full lg:w-auto justify-center"
                onClick={() => navigate('/admin/opd-patients/add-opd')}
              >
                <Plus size={18} /> Add Patient
              </button>
            </div>

      {/* SEARCH + ACTIONS */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
        {/* Search */}
        <input
          type="text"
          placeholder="Search..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="border px-3 py-2 rounded w-full lg:w-64"
        />

        {/* Actions */}
        <div className="flex flex-wrap gap-3 items-center justify-between lg:justify-end">
          <select
            value={limit}
            onChange={(e) => setLimit(e.target.value)}
            className="border px-2 py-2 rounded text-sm"
          >
            <option value={25}>25</option>
            <option value={50}>50</option>
            <option value={100}>100</option>
          </select>

          <div className="flex gap-2">
            <FileText size={18} className="cursor-pointer text-gray-600" />
            <FileSpreadsheet size={18} className="cursor-pointer text-gray-600" />
            <File size={18} className="cursor-pointer text-gray-600" />
            <Printer size={18} className="cursor-pointer text-gray-600" />
          </div>
        </div>
      </div>

      {/* TABLE */}
      <div className="overflow-x-auto">
        <table className="min-w-[1200px] w-full text-sm border-separate border-spacing-0">
          <thead className="bg-gray-50 border-y">
            <tr>
              <th className="px-4 py-2 text-left">OPD No</th>
              <th className="px-4 py-2 text-left">Patient Name</th>
              <th className="px-4 py-2 text-left">Case ID</th>
              <th className="px-4 py-2 text-left">Appointment Date</th>
              <th className="px-4 py-2 text-left">Generated By</th>
              <th className="px-4 py-2 text-left">Doctor</th>
              <th className="px-4 py-2 text-left">Reference</th>
              <th className="px-4 py-2 text-left">Symptoms</th>
              <th className="px-4 py-2 text-left">Old Patient</th>
              <th className="px-4 py-2 text-left">Previous Medical Issue</th>
              <th className="px-4 py-2 text-left">Action</th>
            </tr>
          </thead>
          <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan="8" className="text-center py-6">
                        Loading...
                      </td>
                    </tr>
                  ) : opdList.length === 0 ? (
                    <tr>
                      <td colSpan="8" className="text-center py-10 text-gray-400">
                        No OPD records found
                      </td>
                    </tr>
                  ) : (
                    opdList.map((opd) => (
                      <tr key={opd.opd_id} className="border-t">
                        <td className="p-2">OPDN{opd.opd_id}</td>
                        <td className="p-2 px-6 py-4 text-blue-600 cursor-pointer"
                        onClick={() => navigate(`/admin/opd-patients/${opd.opd_id}`)} >
                          {opd.patient_detail.first_name}{" "}
                          {opd.patient_detail.last_name}
                        </td>
                        <td className="p-2">{opd.case_id}</td>
                        <td className="p-2">
                          {opd.appointment_date
                            ? new Date(opd.appointment_date).toLocaleString()
                            : "-"}
                        </td>
                        <td className="p-2">
                          {opd.created_by_name || "-"}
                        </td>
                        <td className="p-2">
                          {opd.doctor_detail?.full_name || "-"}
                        </td>
                        <td className="p-2">{opd.reference || "-"}</td>
                        <td className="p-2">{opd.symptom_name || "-"}</td>
                        <td className="p-2">{opd.old_patient ? "Yes" : "No"}</td>
                        <td className="p-2">
                          {opd.previous_medical_issue || "-"}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
        </table>
      </div>

            {/* FOOTER */}
            <div className="flex justify-between items-center mt-4 text-sm text-gray-500">
              <span>Records: 0 to 0 of 0</span>
              <div className="flex gap-2">
                <button className="px-2">‹</button>
                <button className="px-2">›</button>
              </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
}
