import React, { useState } from "react";
import Sidebar from "../../components/CommonComponent/Sidebar";
import Navbar from "../../components/AdminComponent/Navbar";
import { useNavigate } from "react-router-dom";
import {
  Plus,
  FileText,
  FileSpreadsheet,
  Printer,
  File,
} from "lucide-react";

const tabs = [
  "Today OPD",
  "Upcoming OPD",
  "Old OPD",
  "Patient View",
];

export default function OpdPatient() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("Today OPD");
  const [search, setSearch] = useState("");
  const [limit, setLimit] = useState(100);

  return (
    <div className="h-screen w-screen flex bg-gray-100 overflow-hidden">
      <Sidebar />

      <div className="flex flex-col flex-1 overflow-hidden">
        <Navbar />

        <main className="flex-1 overflow-y-auto p-4 md:p-6">
          <div className="bg-white rounded-lg shadow border border-gray-200 p-4 md:p-6">

            {/* TABS + ADD BUTTON */}
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
              {/* Tabs */}
             <div className="flex flex-wrap gap-6 text-sm font-medium">
  {tabs.map((tab) => (
    <button
      key={tab}
      onClick={() => setActiveTab(tab)}
      className={`pb-2 transition-colors duration-200 ${
        activeTab === tab
          ? "text-[#6046B5] border-b-2 border-[#6046B5] font-semibold"
          : "text-gray-600 hover:text-[#6046B5]"
      }`}
    >
      {tab}
    </button>
  ))}
</div>



              {/* Add Patient */}
              <button
                className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2]
                           text-white px-4 py-2 rounded
                           flex items-center gap-2
                           w-full lg:w-auto justify-center"
                onClick={() => navigate('/admin/opd-patients/add-opd-visit')}
              >
                <Plus size={18} /> Add Patient
              </button>
            </div>

            {/* SEARCH + ACTIONS */}
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
              {/* Search */}
              <input
                type="text"
                placeholder="Search..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="border px-3 py-2 rounded w-full lg:w-64"
              />

              {/* Actions */}
              <div className="flex flex-wrap gap-3 items-center justify-between lg:justify-end">
                <select
                  value={limit}
                  onChange={(e) => setLimit(e.target.value)}
                  className="border px-2 py-2 rounded text-sm"
                >
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>

                <div className="flex gap-2">
                  <FileText size={18} className="cursor-pointer text-gray-600" />
                  <FileSpreadsheet size={18} className="cursor-pointer text-gray-600" />
                  <File size={18} className="cursor-pointer text-gray-600" />
                  <Printer size={18} className="cursor-pointer text-gray-600" />
                </div>
              </div>
            </div>

            {/* TABLE */}
            <div className="overflow-x-auto">
              <table className="min-w-[1200px] w-full text-sm border-separate border-spacing-0">
                <thead className="bg-gray-50 border-y">
                  <tr>
                    <th className="px-4 py-2 text-left">OPD No</th>
                    <th className="px-4 py-2 text-left">Patient Name</th>
                    <th className="px-4 py-2 text-left">Case ID</th>
                    <th className="px-4 py-2 text-left">Appointment Date</th>
                    <th className="px-4 py-2 text-left">Generated By</th>
                    <th className="px-4 py-2 text-left">Consultant</th>
                    <th className="px-4 py-2 text-left">Reference</th>
                    <th className="px-4 py-2 text-left">Symptoms</th>
                    <th className="px-4 py-2 text-left">Is Antenatal</th>
                    <th className="px-4 py-2 text-left">Previous Medical Issue</th>
                    <th className="px-4 py-2 text-left">Action</th>
                  </tr>
                </thead>

                <tbody>
                  <tr>
                    <td colSpan={11} className="py-12 text-center text-gray-400">
                      <p className="text-red-400 mb-2">
                        No data available in table
                      </p>

                      <div className="flex flex-col items-center gap-2">
                        <img
                          src="https://cdn-icons-png.flaticon.com/512/4076/4076504.png"
                          alt="No data"
                          className="w-28 opacity-80"
                        />
                        <p className="text-green-600 text-sm">
                          ← Add new record or search with different criteria.
                        </p>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* FOOTER */}
            <div className="flex justify-between items-center mt-4 text-sm text-gray-500">
              <span>Records: 0 to 0 of 0</span>
              <div className="flex gap-2">
                <button className="px-2">‹</button>
                <button className="px-2">›</button>
              </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
}
