# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pathology_module', '0001_initial'),
        ('patient_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologybill',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_bills', to='patient_module.medicalcase'),
        ),
    ]
