# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd_ipd_module', '0003_initial'),
        ('pathology_module', '0002_initial'),
        ('patient_module', '0001_initial'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologybill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_bills', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_bills', to='opd_ipd_module.prescription'),
        ),
        migrations.AddField(
            model_name='pathologybillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pathology_module.pathologybill'),
        ),
        migrations.AddField(
            model_name='pathologycategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologyparameter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='pathology_module.pathologycategory'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_tests', to='setup_module.hospitalcharges'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='parameters',
            field=models.ManyToManyField(related_name='tests', to='pathology_module.pathologyparameter'),
        ),
        migrations.AddField(
            model_name='pathologybillitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology_module.pathologytest'),
        ),
    ]
