# Generated by Django 5.2.4 on 2026-01-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0007_medicalcase'),
        ('radiology_module', '0002_drop_extra_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologybill',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_bills', to='patient_module.medicalcase'),
        ),
    ]
