# Generated by Django 5.2.8 on 2026-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_module', '0004_remove_radiologybill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologytest',
            name='report_days',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiologytest',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radiologytest',
            name='test_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
