# Generated by Django 5.2.8 on 2026-01-19 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_module', '0001_initial'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnding', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpdPatient',
            fields=[
                ('ipd_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(blank=True, max_length=20, null=True)),
                ('checkup_id', models.CharField(blank=True, max_length=20, null=True)),
                ('old_patient', models.BooleanField(default=False)),
                ('casualty', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_medical_issue', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_patients_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient')),
                ('symptom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='IpdDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_status', models.CharField(choices=[('normal', 'Normal'), ('referral', 'Referral'), ('death', 'Death')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('investigation', models.TextField(blank=True, null=True)),
                ('operation', models.TextField(blank=True, null=True)),
                ('treatment_at_home', models.TextField(blank=True, null=True)),
                ('discharge_note', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ipd_discharge_attachments/')),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='patient_module.patient')),
                ('ipd_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='opd_ipd_module.ipdpatient')),
            ],
        ),
        migrations.CreateModel(
            name='OpdPatient',
            fields=[
                ('opd_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('transfer to bank account', 'Transfer to Bank Account'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=50)),
                ('checkup_id', models.CharField(max_length=20, unique=True)),
                ('old_patient', models.BooleanField(default=False)),
                ('casualty', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_medical_issue', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='opd_patients_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient')),
                ('symptom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom')),
            ],
        ),
    ]
