# Generated by Django 5.2.8 on 2025-12-20 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_module', '0001_initial'),
        ('doctor_module', '0002_doctor'),
        ('patient_module', '0004_alter_patient_emergency_contact_name_and_more'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('ipd_no', models.CharField(max_length=20, unique=True)),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('old_patient', models.BooleanField(default=False)),
                ('previous_medical_issue', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.bad')),
                ('consutant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OpdPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opd_no', models.CharField(max_length=20, unique=True)),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('old_patient', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('previos_medical_issue', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_module.appointment')),
                ('consutant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient')),
            ],
        ),
    ]
