# Generated by Django 5.2.8 on 2025-12-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='opdpatient',
            old_name='previos_medical_issue',
            new_name='previous_medical_issue',
        ),
        migrations.RemoveField(
            model_name='opdpatient',
            name='consutant_doctor',
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='casualty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='checkup_id',
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='doctor',
            field=models.ForeignKey(default=12, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='opd_patients_as_doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('transfer to bank account', 'Transfer to Bank Account'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='symptom',
            field=models.CharField(default='General Checkup', max_length=100),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
