# Generated by Django 5.2.8 on 2025-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0002_rename_previos_medical_issue_opdpatient_previous_medical_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdpatient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='opdpatient',
            name='opd_no',
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='opd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
