# Generated by Django 5.2.8 on 2026-01-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0002_remove_prescription_fnding_prescription_doctor_and_more'),
        ('pathology_module', '0001_initial'),
        ('pharmacy_module', '0001_initial'),
        ('radiology_module', '0002_drop_extra_columns'),
        ('setup_module', '0004_fix_missing_vital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='finding_category',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='footer_note',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='header_note',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='interval',
        ),
        migrations.AddField(
            model_name='prescription',
            name='Prescribed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pathology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pathology_module.pathologytest'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='radiology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='radiology_module.radiologytest'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine_dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinedosage'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='findings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.finding'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.dosage'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinecategory'),
        ),
    ]
