# Generated by Django 5.2.4 on 2026-01-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0003_remove_prescription_doctor_and_more'),
        ('pathology_module', '0001_initial'),
        ('radiology_module', '0002_drop_extra_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Prescribed_by',
            new_name='prescribed_by',
        ),
        migrations.AddField(
            model_name='prescription',
            name='finding_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pathology',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='radiology',
        ),
        migrations.AddField(
            model_name='prescription',
            name='pathology',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='pathology_module.pathologytest'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='radiology',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='radiology_module.radiologytest'),
        ),
    ]
