# Generated by Django 5.2.8 on 2025-12-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_module', '0005_appointment_doctor'),
        ('opd_ipd_module', '0003_remove_opdpatient_id_remove_opdpatient_opd_no_and_more'),
        ('setup_module', '0002_hospitalcharges_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdpatient',
            name='visit_date',
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment_module.appointment'),
        ),
        migrations.AlterField(
            model_name='opdpatient',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom'),
        ),
    ]
