# Generated by Django 5.2.8 on 2025-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0004_remove_opdpatient_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdpatient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='opdpatient',
            name='appointment',
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='ipd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
