# Generated by Django 5.2.8 on 2026-01-24 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0004_rename_prescribed_by_prescription_prescribed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_notes_created', to=settings.AUTH_USER_MODEL)),
                ('ipd_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='opd_ipd_module.ipdpatient')),
            ],
        ),
    ]
