# Generated by Django 5.2.8 on 2025-12-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0005_remove_ipdpatient_id_remove_opdpatient_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdpatient',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
