# Generated by Django 5.2.4 on 2026-01-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0006_nursenote_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursenote',
            name='opd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='opd_ipd_module.opdpatient'),
        ),
        migrations.AlterField(
            model_name='nursenote',
            name='ipd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='opd_ipd_module.ipdpatient'),
        ),
    ]
