# Generated by Django 5.2.8 on 2025-12-27 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0006_alter_opdpatient_appointment_date'),
        ('setup_module', '0002_hospitalcharges_symptom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdpatient',
            old_name='bad',
            new_name='bed',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='consutant_doctor',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='ipd_no',
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='checkup_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='doctor',
            field=models.ForeignKey(default=0, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_patients_as_doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_module.symptom'),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
