# Generated by Django 5.2.8 on 2026-01-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0007_nursenote_opd_patient_alter_nursenote_ipd_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdpatient',
            old_name='appointment_date',
            new_name='admission_date',
        ),
    ]
