# Generated by Django 5.2.8 on 2025-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0007_rename_bad_ipdpatient_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
