# Generated by Django 5.2.8 on 2025-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0008_ipdpatient_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='casualty',
            field=models.BooleanField(default=False),
        ),
    ]
