# Generated by Django 5.2.8 on 2026-01-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0008_rename_appointment_date_ipdpatient_admission_date'),
        ('patient_module', '0007_medicalcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdpatient',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='opdpatient',
            name='case_id',
        ),
        migrations.AddField(
            model_name='ipdpatient',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='opdpatient',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_visits', to='patient_module.medicalcase'),
        ),
    ]
