# Generated by Django 5.2.8 on 2026-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0009_remove_ipdpatient_case_id_remove_opdpatient_case_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient',
            name='casualty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ipdpatient',
            name='is_discharged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ipdpatient',
            name='old_patient',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
