# Generated by Django 5.2.8 on 2025-12-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0009_ipdpatient_casualty'),
        ('patient_module', '0004_alter_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_status', models.CharField(choices=[('normal', 'Normal'), ('referral', 'Referral'), ('death', 'Death')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('investigation', models.TextField(blank=True, null=True)),
                ('operation', models.TextField(blank=True, null=True)),
                ('treatment_at_home', models.TextField(blank=True, null=True)),
                ('discharge_note', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ipd_discharge_attachments/')),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipd_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='opd_ipd_module.ipdpatient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='patient_module.patient')),
            ],
        ),
    ]
