# Generated by Django 5.2.8 on 2025-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0010_ipddischarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdpatient',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
