import RadiologyRow from "./RadiologyRow";

export default function RadiologyTable({ bills }) {
  return (
    <div className="overflow-x-auto bg-white rounded shadow">
      <table className="min-w-full text-sm">
        <thead className="border-b bg-gray-50">
          <tr className="text-left">
            <th className="p-2">Bill No</th>
            <th className="p-2">Case ID</th>
            <th className="p-2">Bill Date</th>
            <th className="p-2">Patient</th>
            <th className="p-2">Generated By</th>
            <th className="p-2">Reference Doctor</th>
            <th className="p-2">Report</th>
            <th className="p-2">Amount ($)</th>
            <th className="p-2">Discount ($)</th>
            <th className="p-2">Tax ($)</th>
            <th className="p-2">Net Amount ($)</th>
            <th className="p-2">Paid ($)</th>
            <th className="p-2">Balance ($)</th>
            <th className="p-2 text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          {bills.map((item, index) => (
            <RadiologyRow key={index} data={item} />
          ))}
        </tbody>
      </table>
    </div>
  );
}
