# Generated by Django 5.2.8 on 2025-12-14 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        ('patient_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_no', models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True)),
                ('appointment_date', models.DateTimeField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10, null=True)),
                ('slot', models.CharField(blank=True, max_length=20, null=True)),
                ('appontmet_priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('very urgent', 'Very Urgent'), ('low', 'Low')], default='normal', max_length=15)),
                ('payment_modee', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('live_consultation', models.BooleanField(default=False)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.adminprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_module.patient')),
            ],
        ),
    ]
