# Generated by Django 5.2.8 on 2026-01-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_module', '0001_initial'),
        ('setup_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='setup_module.hospitalcharges'),
        ),
    ]
