# Generated by Django 5.2.8 on 2025-12-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
