# Generated by Django 5.2.8 on 2025-12-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_module', '0003_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
