# Generated by Django 5.2.8 on 2026-01-01 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_module', '0005_appointment_doctor'),
        ('patient_module', '0004_alter_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient_module.patient'),
        ),
    ]
