# Generated by Django 5.2.8 on 2026-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='year_made',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
