# Generated by Django 5.2.4 on 2026-01-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancebill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
