# Generated by Django 5.2.8 on 2026-01-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0003_ambulancebill_hospital_charge'),
        ('setup_module', '0003_rename_bad_bed_rename_bad_group_bed_bed_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ambulancecharge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ambulancecharge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ambulancecharge',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='ambulancebill',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_bills', to='setup_module.hospitalcharges'),
        ),
        migrations.RemoveField(
            model_name='ambulancebill',
            name='hospital_charge',
        ),
        migrations.DeleteModel(
            name='AmbulanceChargeCategory',
        ),
        migrations.DeleteModel(
            name='AmbulanceCharge',
        ),
    ]
