# Generated by Django 5.2.4 on 2026-02-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0003_ambulancebill_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancebill',
            name='bill_no',
        ),
    ]
