# Generated by Django 5.2.8 on 2026-01-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0004_alter_ambulancecharge_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancebill',
            old_name='charge',
            new_name='hospital_charge',
        ),
    ]
