# Generated by Django 5.2.8 on 2026-01-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0006_ambulancebilltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancebill',
            name='bill_no',
        ),
    ]
