import ItemStockRow from "./ItemStockRow";

export default function ItemStockTable({ data }) {
  return (
    <div className="overflow-x-auto bg-white rounded shadow">
      <table className="min-w-full text-sm">
        <thead className="bg-gray-100">
          <tr>
            <th className="p-2 text-left">Name</th>
            <th className="p-2">Category</th>
            <th className="p-2">Supplier</th>
            <th className="p-2">Store</th>
            <th className="p-2">Date</th>
            <th className="p-2">Description</th>
            <th className="p-2">Total Qty</th>
            <th className="p-2">Generated By</th>
            <th className="p-2">Price ($)</th>
          </tr>
        </thead>

        <tbody>
          {data.map((item) => (
            <ItemStockRow key={item.id} item={item} />
          ))}
        </tbody>
      </table>
    </div>
  );
}
