# Generated by Django 5.2.8 on 2025-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('pathologist', 'Pathologist'), ('radiologist', 'Radiologist'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('staff', 'Staff')], default='patient', max_length=20),
        ),
    ]
