# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory_module.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemissue',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemissue',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemissuedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_module.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemissuedetail',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_module.itemissue'),
        ),
        migrations.AddField(
            model_name='itemissuedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_module.item'),
        ),
        migrations.AddField(
            model_name='itemreturn',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.itemissue'),
        ),
        migrations.AddField(
            model_name='itemreturn',
            name='returned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_module.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory_module.item'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_module.itemstore'),
        ),
        migrations.AddField(
            model_name='itemstorestock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.item'),
        ),
        migrations.AddField(
            model_name='itemstorestock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_module.itemstore'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_module.itemsupplier'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='itemstorestock',
            unique_together={('item', 'store')},
        ),
    ]
