/**
 * Common Utility for Printing Professional Medical Reports
 */

export const printReport = ({
    title = "Report",
    headerImg = "",
    footerText = "",
    content = "",
    customStyles = "",
}) => {
    const printWindow = window.open("", "_blank");

    // Standard Global Print Styles
    const globalStyles = `
        @page { size: A4; margin: 10mm; }
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            margin: 0; 
            padding: 0; 
            color: #333; 
            line-height: 1.5;
        }
        .header-container { width: 100%; text-align: center; margin-bottom: 10px; }
        .header-img { width: 100%; max-height: 150px; object-fit: contain; }
        .default-header { 
            padding: 20px; 
            background: #6046B5; 
            color: white; 
            text-align: center;
            border-radius: 0 0 10px 10px;
        }
        .default-header h1 { margin: 0; font-size: 28px; letter-spacing: 1px; }
        
        .content-body { padding: 20px 40px; }
        
        .report-section-title {
            font-size: 16px;
            font-weight: 800;
            color: #6046B5;
            border-bottom: 2px solid #6046B5;
            margin: 25px 0 12px 0;
            padding-bottom: 5px;
            text-transform: uppercase;
        }

        .data-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-bottom: 25px;
        }
        
        .data-item { display: flex; font-size: 13px; border-bottom: 1px solid #f0f0f0; padding: 4px 0; }
        .data-label { font-weight: 700; width: 140px; color: #666; }
        .data-value { font-weight: 600; color: #111; }

        table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 13px; }
        th { background: #f8f9fa; text-align: left; padding: 10px; border-bottom: 2px solid #6046B5; color: #6046B5; font-weight: 800; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        
        .signature-section {
            margin-top: 60px;
            display: flex;
            justify-content: space-between;
            padding: 0 40px;
        }
        .sig-box {
            text-align: center;
            width: 180px;
        }
        .sig-line {
            border-top: 1px solid #333;
            margin-bottom: 5px;
        }
        .sig-label {
            font-size: 12px;
            font-weight: 700;
            color: #555;
        }

        .footer { 
            position: fixed; 
            bottom: 0; 
            left: 0; 
            right: 0; 
            padding: 15px 40px; 
            text-align: center; 
            font-size: 11px; 
            border-top: 1px dotted #ccc; 
            background: white;
            color: #777;
        }

        @media print {
            .no-print { display: none; }
            body { padding-bottom: 60px; }
            .footer { position: fixed; bottom: 0; }
        }
    `;

    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
            <head>
                <title>${title}</title>
                <style>
                    ${globalStyles}
                    ${customStyles}
                </style>
            </head>
            <body>
                <div class="header-container">
                    ${headerImg
            ? `<img src="${headerImg}" class="header-img" alt="Hospital Header" />`
            : `<div class="default-header"><h1>HOSPITAL MANAGEMENT SYSTEM</h1></div>`
        }
                </div>

                <div class="content-body">
                    ${content}
                </div>

                <div class="footer">
                    ${footerText || "Generated by Digital Health Management System"}
                </div>

                <script>
                    window.onload = function() {
                        const images = document.getElementsByTagName('img');
                        let loadedCount = 0;
                        const totalImages = images.length;

                        const doPrint = () => {
                            setTimeout(() => {
                                window.print();
                                window.close();
                            }, 500);
                        };

                        if (totalImages === 0) {
                            doPrint();
                        } else {
                            for (let i = 0; i < totalImages; i++) {
                                if (images[i].complete) {
                                    loadedCount++;
                                    if (loadedCount === totalImages) doPrint();
                                } else {
                                    images[i].onload = () => {
                                        loadedCount++;
                                        if (loadedCount === totalImages) doPrint();
                                    };
                                    images[i].onerror = () => {
                                        loadedCount++;
                                        if (loadedCount === totalImages) doPrint();
                                    };
                                }
                            }
                        }
                    };
                </script>
            </body>
        </html>
    `);

    printWindow.document.close();
};
