import React, { useEffect, useState } from "react";
import { X } from "lucide-react";
import { getPathologyBillDetail } from "../../api/pathologyApi";
import { useNotify } from "../../context/NotificationContext";

export default function PathologyBillDetails({ open, billId, onClose }) {
  const notify = useNotify();

  // ✅ default structure to avoid crashes
  const [bill, setBill] = useState({
    items: [],
  });
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!open || !billId) return;

    const fetchDetail = async () => {
      try {
        setLoading(true);
        const res = await getPathologyBillDetail(billId);
        const data = res?.data || res;

        // ✅ normalize items array (backend returns 'items' not 'tests')
        setBill({
          ...data,
          items: data?.items || [],
        });
      } catch (err) {
        const errorMsg = err?.response?.data?.error || err?.message || "Failed to load bill details";
        notify("error", errorMsg);
        onClose();
      } finally {
        setLoading(false);
      }
    };

    fetchDetail();
  }, [open, billId, notify, onClose]);

  if (!open) return null;

  if (loading) {
    return (
      <div className="fixed inset-0 bg-white z-50 flex items-center justify-center">
        Loading bill details...
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-white z-50 flex flex-col">
      {/* ================= HEADER ================= */}
      <div className="bg-gradient-to-r from-[#6046B5] to-[#8A63D2] text-white px-4 py-2 flex justify-between items-center">
        <h2 className="font-semibold text-xl">Bill Details</h2>
        <div className="flex gap-3">
          <X
            size={18}
            className="cursor-pointer"
            onClick={onClose}
          />
        </div>
      </div>

      {/* ================= BODY ================= */}
      <div className="p-4 text-sm space-y-6 overflow-y-auto">

        {/* DETAILS GRID */}
        <div className="grid md:grid-cols-3 gap-6">
          <Detail label="Bill No" value={bill.id} />
          <Detail label="Case ID" value={bill.case_id || "-"} />
          <Detail label="Patient Name" value={bill.patient_name || "-"} />

          <Detail label="Prescription ID" value={bill.prescription_id ? `#${bill.prescription_id}` : "-"} />
          <Detail label="Age" value={bill.patient_age !== null && bill.patient_age !== undefined ? `${bill.patient_age} years` : "-"} />
          <Detail label="Gender" value={bill.patient_gender || "-"} />

          <Detail label="Doctor Name" value={bill.doctor_name || "-"} />
          <Detail label="Mobile No" value={bill.patient_phone || "-"} />
          <Detail label="Email" value={bill.patient_email || "-"} />

          <Detail label="Blood Group" value={bill.patient_blood_group || "-"} />
          <Detail label="Address" value={bill.patient_address || "-"} />
          <Detail label="Generated By" value={bill.created_by_name || "-"} />

        </div>

        {/* FINANCIAL SUMMARY */}
        <div className="grid md:grid-cols-3 gap-6 border-t pt-4">
          <div />
          <div />
          <div>
            <Detail label="Subtotal ($)" value={bill.subtotal ? `$${Number(bill.subtotal).toFixed(2)}` : "-"} />
            <Detail label="Discount ($)" value={bill.discount ? `$${Number(bill.discount).toFixed(2)}` : "-"} />
            <Detail label="Tax ($)" value={bill.tax ? `$${Number(bill.tax).toFixed(2)}` : "-"} />
            <Detail label="Net Amount ($)" value={bill.total_amount ? `$${Number(bill.total_amount).toFixed(2)}` : "-"} bold />
            <Detail label="Paid Amount ($)" value={bill.paid_amount ? `$${Number(bill.paid_amount).toFixed(2)}` : "-"} />
            <Detail 
              label="Balance ($)" 
              value={bill.balance !== null && bill.balance !== undefined ? `$${Number(bill.balance).toFixed(2)}` : "-"}
              className={bill.balance > 0 ? "text-red-600 font-semibold" : bill.balance === 0 ? "text-green-600 font-semibold" : ""}
            />
            <Detail label="Payment Mode" value={bill.payment_mode ? bill.payment_mode.charAt(0).toUpperCase() + bill.payment_mode.slice(1) : "-"} />
          </div>
        </div>

        {/* TEST TABLE */}
        <div className="overflow-x-auto">
          <table className="w-full border text-sm">
            <thead className="bg-gray-100">
              <tr>
                <Th>#</Th>
                <Th>Test Name</Th>
                <Th>Report Days</Th>
                <Th>Report Date</Th>
                <Th>Price ($)</Th>
                <Th>Tax ($)</Th>
                <Th>Total ($)</Th>
              </tr>
            </thead>
            <tbody>
              {bill.items && bill.items.length > 0 ? (
                bill.items.map((item, i) => {
                  const total = Number(item.price || 0) + Number(item.tax || 0);
                  return (
                    <tr key={item.id || i} className="hover:bg-gray-50">
                      <Td>{i + 1}</Td>
                      <Td className="font-medium">
                        {item.test_name || "-"}
                      </Td>
                      <Td>{item.report_days ? `${item.report_days} days` : "-"}</Td>
                      <Td>
                        {item.report_date 
                          ? new Date(item.report_date).toLocaleDateString() 
                          : "-"}
                      </Td>
                      <Td>${Number(item.price || 0).toFixed(2)}</Td>
                      <Td>${Number(item.tax || 0).toFixed(2)}</Td>
                      <Td className="font-semibold">${total.toFixed(2)}</Td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td
                    colSpan={7}
                    className="text-center py-4 text-gray-500"
                  >
                    No tests found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

/* ================= SMALL COMPONENTS ================= */

const Detail = ({ label, value, bold, className = "" }) => (
  <div className="grid grid-cols-2 gap-2 py-1">
    <span className="text-gray-600 font-bold">{label}:</span>
    <span className={`${bold ? "font-bold" : ""} ${className}`}>
      {value ?? "-"}
    </span>
  </div>
);

const Th = ({ children }) => (
  <th className="border px-2 py-1 text-left font-semibold">
    {children}
  </th>
);

const Td = ({ children, className = "" }) => (
  <td className={`border px-2 py-2 align-top ${className}`}>
    {children}
  </td>
);
