import PathologyRow from "./PathologyRow";

export default function PathologyTable({ bills }) {
  return (
    <div className="bg-white rounded-lg shadow overflow-x-auto">
      <table className="min-w-full text-left">
        <thead className="bg-gray-100 text-sm">
          <tr>
            <th className="px-3 py-2">Bill No</th>
            <th className="px-3 py-2">Case ID</th>
            <th className="px-3 py-2">Bill Date</th>
            <th className="px-3 py-2">Patient</th>
            <th className="px-3 py-2">Generated By</th>
            <th className="px-3 py-2">Doctor</th>
            <th className="px-3 py-2 text-right">Net Amount</th>
            <th className="px-3 py-2 text-right">Paid</th>
            <th className="px-3 py-2 text-right">Balance</th>

          </tr>
        </thead>

        <tbody>
          {bills.length === 0 ? (
            <tr>
              <td colSpan="9" className="text-center py-6 text-gray-500">
                No records found
              </td>
            </tr>
          ) : (
            bills.map((bill) => (
              <PathologyRow key={bill.billNo} bill={bill} />
            ))
          )}
        </tbody>
      </table>
    </div>
  );
}
