# Generated by Django 5.2.8 on 2026-01-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('composition', models.CharField(blank=True, max_length=255)),
                ('min_level', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('box_packing', models.CharField(max_length=50)),
                ('vat_account', models.CharField(blank=True, max_length=50)),
                ('rack_number', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.medicinecategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_module.medicinegroup')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_module.unit')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
    ]
