# Generated by Django 5.2.4 on 2026-01-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0007_medicalcase'),
        ('pharmacy_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybill',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='patient_module.medicalcase'),
        ),
    ]
