# Generated by Django 5.2.8 on 2026-01-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0002_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinecategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
