# Generated by Django 5.2.8 on 2026-01-08 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0004_medicinebatch_medicinestock_pharmacybill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
