# Generated by Django 5.2.8 on 2026-01-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0005_medicinecategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacybill',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='pharmacypurchase',
            name='purchase_no',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='pharmacy_module.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy_module.medicine'),
        ),
        migrations.AlterField(
            model_name='medicinedosage',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_doases', to='pharmacy_module.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicinedosage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_dosages', to='pharmacy_module.unit'),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacy_module.medicinebatch'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinestock',
            unique_together={('medicine', 'batch')},
        ),
    ]
