# Generated by Django 5.2.8 on 2026-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0006_remove_pharmacybill_bill_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacybill',
            name='id',
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='bill_no',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
