# Generated by Django 5.2.8 on 2026-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_module', '0007_remove_pharmacybill_id_pharmacybill_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacybill',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
