import { useEffect, useMemo, useState } from "react";
import {Pencil, Trash2} from "lucide-react";
import { useNavigate } from "react-router-dom";
import AdminLayout from "../../layout/AdminLayout";
import AddItemStock from "../../components/Inventory/AddItemStock";
import UpdateItemStock from "../../components/Inventory/UpdateItemStock";
import { getItemStock, deleteItemStock  } from "../../api/inventoryApi";
import { useNotify } from "../../context/NotificationContext";

export default function ItemStockPage() {
  const navigate = useNavigate();
  const notify = useNotify();
  const [search, setSearch] = useState("");
  const [openAdd, setOpenAdd] = useState(false);
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [editStock, setEditStock] = useState(null);


  /* ================= FETCH STOCK ================= */
  const loadStock = async () => {
    try {
      setLoading(true);
      const res = await getItemStock();
      setData(res.data);
    } catch (err) {
      console.error("Stock fetch failed", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadStock();
  }, []);

  /* ================= SEARCH ================= */
  const filteredData = useMemo(() => {
    return data.filter((item) =>
      item.item_name?.toLowerCase().includes(search.toLowerCase())
    );
  }, [search, data]);


  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this stock?")) return;
  
    try {
      await deleteItemStock(id);
      notify("success", "Stock deleted successfully");
      await loadStock();
    } catch (err) {
      notify("error", "Failed to delete stock");
    }
  };
  


  return (
    <AdminLayout>
      <div className="min-h-full p-1">

        {/* ================= HEADER ================= */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between bg-white gap-3 p-4 mb-4">
          <div>
            <h2 className="text-2xl font-semibold text-black pb-4">
              Item Stock List
            </h2>

            <input
              type="text"
              placeholder="Search item..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="border px-3 py-2 rounded w-full sm:w-64"
            />
          </div>

          <div className="flex gap-2">
            <button
              onClick={() => setOpenAdd(true)}
              className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-3 py-2 rounded"
            >
              + Add Item Stock
            </button>

            <button
              onClick={() => navigate("/admin/Inventory/Issue-Item")}
              className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-3 py-2 rounded"
            >
              Issue Item
            </button>

            <button
              onClick={() => navigate("/admin/Inventory/Item-List")}
              className="bg-gradient-to-b from-[#6046B5] to-[#8A63D2] text-white px-3 py-2 rounded"
            >
              Item
            </button>
          </div>
        </div>

        {/* ================= TABLE ================= */}
        <div className="overflow-x-auto bg-white rounded shadow">
          <table className="min-w-full text-sm">
            <thead className="bg-gray-100">
              <tr>
                <th className="p-2 text-left">Name</th>
                <th className="p-2 text-left">Category</th>
                <th className="p-2 text-left">Supplier</th>
                <th className="p-2 text-left">Store</th>
                <th className="p-2 text-left">Date</th>
                <th className="p-2 text-left">Description</th>
                <th className="p-2 text-left">Total Qty</th>
                <th className="p-2 text-left">Generated By</th>
                <th className="p-2 text-left">Price ($)</th>
                <th className="p-2 text-left">Action</th>
              </tr>
            </thead>

            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="9" className="text-center p-4">
                    Loading...
                  </td>
                </tr>
              ) : filteredData.length === 0 ? (
                <tr>
                  <td colSpan="9" className="text-center p-4">
                    No stock found
                  </td>
                </tr>
              ) : (
                filteredData.map((item) => (
                  <tr key={item.id} className="hover:bg-gray-100">
                    <td className="p-2 text-blue-600 text-left">{item.item_name}</td>
                    <td className="p-2 text-left">{item.category_name}</td>
                    <td className="p-2 text-left">{item.supplier_name}</td>
                    <td className="p-2 text-left">{item.store_name}</td>
                    <td className="p-2 text-left">{new Date(item.stock_date).toLocaleDateString()}</td>
                    <td className="p-2 text-left">{item.description}</td>
                    <td className="p-2 text-left">{item.quantity}</td>
                    <td className="p-2 text-left">{item.created_by_name}</td>
                    <td className="p-2 text-left">₹{item.purchase_price}</td>
                     <td className="p-3 text-left flex gap-2">
                    <button
                      onClick={() => setEditStock(item)}
                      className="bg-green-100 p-2 rounded text-green-600 hover:bg-green-200"
                    >
                      <Pencil size={16} />
                    </button>

                    <button
                      onClick={() => handleDelete(item.id)}
                      className="bg-red-100 p-2 rounded text-red-600 hover:bg-red-200"
                    >
                      <Trash2 size={16} />
                    </button>
                  </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ================= ADD MODAL ================= */}
      <AddItemStock
        open={openAdd}
        onClose={() => setOpenAdd(false)}
        refresh={loadStock}
      />
      {/* UPDATE MODAL */}
      {editStock && (
        <UpdateItemStock
          open={true}
          stock={editStock}
          onClose={() => setEditStock(null)}
          refresh={loadStock}
        />
      )}
    </AdminLayout>
  );
}
