# Generated by Django 5.2.8 on 2025-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_name', models.CharField(max_length=50, unique=True)),
                ('bad_type', models.CharField(default='Normal', max_length=50)),
                ('bad_group', models.CharField(default='General', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
