# Generated by Django 5.2.8 on 2025-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=100, unique=True)),
                ('charge_category', models.CharField(max_length=100)),
                ('charge_type', models.CharField(max_length=100)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_description', models.TextField(blank=True, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_title', models.CharField(max_length=100, unique=True)),
                ('symptom_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
