# Generated by Django 5.2.8 on 2025-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0007_rename_bad_ipdpatient_bed_and_more'),
        ('setup_module', '0002_hospitalcharges_symptom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bad',
            new_name='Bed',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bad_group',
            new_name='bed_group',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bad_name',
            new_name='bed_name',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bad_type',
            new_name='bed_type',
        ),
    ]
