# Generated by Django 5.2.4 on 2026-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_module', '0004_fix_missing_vital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('appointment_footer', models.TextField(blank=True, null=True)),
                ('opd_prescription_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('opd_prescription_footer', models.TextField(blank=True, null=True)),
                ('ipd_prescription_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('ipd_prescription_footer', models.TextField(blank=True, null=True)),
                ('opd_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('opd_bill_footer', models.TextField(blank=True, null=True)),
                ('ipd_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('ipd_bill_footer', models.TextField(blank=True, null=True)),
                ('pharmacy_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('pharmacy_bill_footer', models.TextField(blank=True, null=True)),
                ('pathology_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('pathology_bill_footer', models.TextField(blank=True, null=True)),
                ('radiology_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('radiology_bill_footer', models.TextField(blank=True, null=True)),
                ('ambulance_bill_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('ambulance_bill_footer', models.TextField(blank=True, null=True)),
                ('bill_summary_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('bill_summary_footer', models.TextField(blank=True, null=True)),
                ('operation_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('operation_footer', models.TextField(blank=True, null=True)),
                ('birth_record_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('birth_record_footer', models.TextField(blank=True, null=True)),
                ('death_record_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('death_record_footer', models.TextField(blank=True, null=True)),
                ('patient_discharge_header', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('patient_discharge_footer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
