import React, { useEffect, useState } from "react";
import { X } from "lucide-react";
import { getAmbulanceBillDetail } from "../../api/ambulanceApi";
import { useNotify } from "../../context/NotificationContext";

const Detail = ({ label, value, bold = false, className = "" }) => (
  <div className={`${className}`}>
    <div className="text-gray-600 text-xs mb-1">{label}</div>
    <div className={`${bold ? "font-bold" : ""} text-gray-800`}>{value || "-"}</div>
  </div>
);

export default function AmbulanceBillDetail({ open, billId, onClose }) {
  const notify = useNotify();
  const [bill, setBill] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!open || !billId) return;

    const fetchDetail = async () => {
      try {
        setLoading(true);
        const res = await getAmbulanceBillDetail(billId);
        setBill(res.data);
      } catch (err) {
        const errorMsg = err?.response?.data?.error || err?.message || "Failed to load bill details";
        notify("error", errorMsg);
        onClose();
      } finally {
        setLoading(false);
      }
    };

    fetchDetail();
  }, [open, billId, notify, onClose]);

  if (!open) return null;

  if (loading) {
    return (
      <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center">
        <div className="bg-white p-6 rounded-lg">
          Loading bill details...
        </div>
      </div>
    );
  }

  if (!bill) return null;

  // Format date
  const formatDate = (dateString) => {
    if (!dateString) return "-";
    const date = new Date(dateString);
    return date.toLocaleString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });
  };

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-lg w-full max-w-4xl max-h-[90vh] flex flex-col">
        {/* HEADER */}
        <div className="bg-gradient-to-r from-[#6046B5] to-[#8A63D2] text-white px-6 py-4 flex justify-between items-center rounded-t-lg">
          <h2 className="font-semibold text-xl">Ambulance Bill Details</h2>
          <X size={20} className="cursor-pointer hover:bg-white/20 rounded p-1" onClick={onClose} />
        </div>

        {/* BODY */}
        <div className="p-6 overflow-y-auto flex-1">
          <div className="space-y-6">
            {/* BILL INFO */}
            <div className="grid md:grid-cols-3 gap-4">
              <Detail label="Bill No" value={bill.bill_no || `#${bill.id}`} />
              <Detail label="Patient Name" value={bill.patient_name || "-"} />
              <Detail label="Patient Phone" value={bill.patient_phone || "-"} />
              <Detail label="Date" value={formatDate(bill.date)} />
              <Detail label="Generated By" value={bill.created_by_name || "-"} />
              <Detail label="Payment Mode" value={bill.payment_mode ? bill.payment_mode.charAt(0).toUpperCase() + bill.payment_mode.slice(1) : "-"} />
            </div>

            {/* AMBULANCE DETAILS */}
            {bill.ambulance_details && (
              <div className="border-t pt-4">
                <h3 className="font-semibold text-gray-800 mb-3">Ambulance Details</h3>
                <div className="grid md:grid-cols-3 gap-4">
                  <Detail label="Vehicle Number" value={bill.ambulance_details.vehicle_number} />
                  <Detail label="Vehicle Model" value={bill.ambulance_details.vehicle_model} />
                  <Detail label="Driver Name" value={bill.ambulance_details.driver_name} />
                  <Detail label="Driver Contact" value={bill.ambulance_details.driver_contact} />
                </div>
              </div>
            )}

            {/* CHARGE DETAILS */}
            {bill.charge_details && (
              <div className="border-t pt-4">
                <h3 className="font-semibold text-gray-800 mb-3">Charge Details</h3>
                <div className="grid md:grid-cols-3 gap-4">
                  <Detail label="Category" value={bill.charge_details.category} />
                  <Detail label="Charge Name" value={bill.charge_details.charge_name} />
                  <Detail label="Standard Charge ($)" value={bill.charge_details.standard_charge ? `$${Number(bill.charge_details.standard_charge).toFixed(2)}` : "-"} />
                  {bill.charge_details.tax !== undefined && (
                    <Detail label="Tax ($)" value={bill.charge_details.tax ? `$${Number(bill.charge_details.tax).toFixed(2)}` : "-"} />
                  )}
                </div>
              </div>
            )}

            {/* NOTE */}
            {bill.note && (
              <div className="border-t pt-4">
                <Detail label="Note" value={bill.note} />
              </div>
            )}

            {/* FINANCIAL SUMMARY */}
            <div className="border-t pt-4">
              <h3 className="font-semibold text-gray-800 mb-3">Financial Summary</h3>
              <div className="grid md:grid-cols-2 gap-4 max-w-md">
                <Detail label="Total Amount ($)" value={bill.total_amount ? `$${Number(bill.total_amount).toFixed(2)}` : "-"} />
                <Detail label="Discount ($)" value={bill.discount ? `$${Number(bill.discount).toFixed(2)}` : "-"} />
                <Detail label="Tax ($)" value={bill.tax ? `$${Number(bill.tax).toFixed(2)}` : "-"} />
                <Detail label="Net Amount ($)" value={bill.net_amount ? `$${Number(bill.net_amount).toFixed(2)}` : "-"} bold />
                <Detail label="Paid Amount ($)" value={bill.paid_amount ? `$${Number(bill.paid_amount).toFixed(2)}` : "-"} />
                <Detail 
                  label="Balance ($)" 
                  value={bill.balance !== null && bill.balance !== undefined ? `$${Number(bill.balance).toFixed(2)}` : "-"}
                  className={bill.balance > 0 ? "text-red-600 font-semibold" : bill.balance === 0 ? "text-green-600 font-semibold" : ""}
                />
              </div>
            </div>
          </div>
        </div>

        {/* FOOTER */}
        <div className="border-t px-6 py-4 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
