import AmbulanceRow from "./AmbulanceRow";

export default function AmbulanceTable({ data }) {
  return (
    <div className="overflow-x-auto bg-white rounded shadow mt-4">
      <table className="min-w-[1400px] w-full text-left">
        <thead className="bg-gray-100 text-xs font-semibold">
          <tr>
            {[
              "Bill No",
              "Case ID",
              "Patient",
              "Generated By",
              "Vehicle No",
              "Model",
              "Driver",
              "Contact",
              "Address",
              "Date",
              "Amount",
              "Discount",
              "Tax",
              "Net",
              "Paid",
              "Balance",
              "Actions",
            ].map((h) => (
              <th key={h} className="px-3 py-2">
                {h}
              </th>
            ))}
          </tr>
        </thead>

        <tbody>
          {data.length === 0 ? (
            <tr>
              <td colSpan="16" className="text-center py-6 text-gray-500">
                No Records Found
              </td>
            </tr>
          ) : (
            data.map((row, i) => <AmbulanceRow key={i} row={row} />)
          )}
        </tbody>
      </table>
    </div>
  );
}
