import React, { useState, useEffect } from "react";
import { X } from "lucide-react";
import { getAmbulanceBillDetail, updateAmbulanceBill } from "../../api/ambulanceApi";
import { useNotify } from "../../context/NotificationContext";

const formatAmount = (value) => {
    const num = Number.parseFloat(value);
    return Number.isNaN(num) ? "0.00" : num.toFixed(2);
  };
  

/* ---------- Reusable Row ---------- */
const InfoRow = ({ label, value }) => (
  <div className="flex justify-between text-sm py-1 border-b">
    <span className="text-gray-600">{label}</span>
    <span className="font-medium text-gray-900">{value || "-"}</span>
  </div>
);

export default function UpdateAmbulance({ open, onClose, billId, onSuccess }) {
  const notify = useNotify();
  const [loading, setLoading] = useState(false);
  const [bill, setBill] = useState(null);
  const [form, setForm] = useState({
    date: "",
    amount: "",
    mode: "cash",
    note: "",
  });

  useEffect(() => {
    if (open && billId) {
      loadBill();
    } else {
      setBill(null);
      setForm({ date: "", amount: "", mode: "cash", note: "" });
    }
  }, [open, billId]);

  const loadBill = async () => {
    try {
      setLoading(true);
      const res = await getAmbulanceBillDetail(billId);
      const billData = res.data;
      setBill(billData);
      
      // Pre-fill form with current bill data
      setForm({
        date: billData.date || new Date().toISOString().split('T')[0],
        amount: billData.balance || billData.net_amount || "",
        mode: billData.payment_mode || "cash",
        note: billData.note || "",
      });
    } catch (error) {
      notify("error", "Failed to load bill details");
      onClose();
    } finally {
      setLoading(false);
    }
  };

  if (!open) return null;

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async () => {
    if (!bill || !form.date) {
      notify("error", "Please fill in all required fields");
      return;
    }

    try {
      setLoading(true);
      
      // Calculate new paid amount if payment amount is provided
      let newPaidAmount = parseFloat(bill.paid_amount) || 0;
      if (form.amount && parseFloat(form.amount) > 0) {
        newPaidAmount = parseFloat(bill.paid_amount) + parseFloat(form.amount);
      }
      
      const updateData = {
        date: form.date,
        note: form.note || bill.note || "",
        payment_mode: form.mode,
        total_amount: bill.total_amount || 0,
        discount: bill.discount || 0,
        tax: bill.tax || 0,
        paid_amount: newPaidAmount,
      };

      await updateAmbulanceBill(bill.id, updateData);
      notify("success", "Bill updated successfully");
      onSuccess?.();
    } catch (error) {
      notify("error", error?.response?.data?.message || error?.response?.data?.error || "Failed to update bill");
    } finally {
      setLoading(false);
    }
  };

  if (loading && !bill) {
    return (
      <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
        <div className="bg-white p-6 rounded">Loading...</div>
      </div>
    );
  }

  if (!bill) return null;

  return (
    <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
      <div className="bg-white w-full max-w-5xl rounded shadow-lg">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-2 bg-blue-500 text-white">
          <h2 className="text-sm font-semibold">Payments</h2>
          <button onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div className="p-4 grid grid-cols-3 gap-4">
          {/* Left Info */}
          <div className="col-span-1 space-y-1">
            <InfoRow label="Bill No" value={bill.bill_no || `#${bill.id}`} />
            <InfoRow label="Patient" value={`${bill.patient_name || "-"} (${bill.patient_phone || "-"})`} />
            <InfoRow label="Vehicle Number" value={bill.ambulance_details?.vehicle_number || "-"} />
            <InfoRow label="Vehicle Model" value={bill.ambulance_details?.vehicle_model || "-"} />
            <InfoRow label="Driver Name" value={bill.ambulance_details?.driver_name || "-"} />
            <InfoRow label="Driver Contact" value={bill.ambulance_details?.driver_contact || "-"} />
            <InfoRow label="Date" value={bill.date ? new Date(bill.date).toLocaleDateString() : "-"} />
            <InfoRow label="Generated By" value={bill.created_by_name || "-"} />
          </div>

          {/* Amount Summary */}
          <div className="col-span-1 space-y-1">
          <InfoRow label="Amount" value={`$${formatAmount(bill.total_amount)}`} />
<InfoRow label="Discount" value={`$${formatAmount(bill.discount)}`} />
<InfoRow label="Tax" value={`$${formatAmount(bill.tax)}`} />
<InfoRow label="Net Amount" value={`$${formatAmount(bill.net_amount)}`} />
<InfoRow label="Paid Amount" value={`$${formatAmount(bill.paid_amount)}`} />
<InfoRow label="Balance Amount" value={`$${formatAmount(bill.balance)}`} />
</div>
          {/* Payment Form */}
          <div className="col-span-1 space-y-3">
            <div>
              <label className="text-xs text-gray-600">Date *</label>
              <input
                type="date"
                name="date"
                value={form.date}
                onChange={handleChange}
                className="w-full border rounded px-2 py-1 text-sm"
              />
            </div>

            <div>
              <label className="text-xs text-gray-600">Amount ($) *</label>
              <input
                type="number"
                name="amount"
                value={form.amount}
                onChange={handleChange}
                className="w-full border rounded px-2 py-1 text-sm"
              />
            </div>

            <div>
              <label className="text-xs text-gray-600">Payment Mode</label>
              <select
                name="mode"
                value={form.mode}
                onChange={handleChange}
                className="w-full border rounded px-2 py-1 text-sm"
              >
                <option>Cash</option>
                <option>UPI</option>
                <option>Card</option>
                <option>Bank Transfer</option>
              </select>
            </div>

            <div>
              <label className="text-xs text-gray-600">Note</label>
              <textarea
                name="note"
                value={form.note}
                onChange={handleChange}
                rows="3"
                className="w-full border rounded px-2 py-1 text-sm"
              />
            </div>

            <div className="flex justify-end gap-2">
              <button
                onClick={onClose}
                className="bg-gray-300 text-gray-800 text-sm px-4 py-1 rounded hover:bg-gray-400"
                disabled={loading}
              >
                Cancel
              </button>
              <button
                onClick={handleSubmit}
                disabled={loading}
                className="bg-blue-500 text-white text-sm px-4 py-1 rounded hover:bg-blue-600 disabled:opacity-50"
              >
                {loading ? "Saving..." : "Save"}
              </button>
            </div>
          </div>
        </div>

        {/* Transaction History */}
        <div className="px-4 pb-4">
          <h3 className="text-sm font-semibold mb-2">Transaction History</h3>

          <table className="w-full text-sm border">
            <thead className="bg-gray-100">
              <tr>
                <th className="border px-2 py-1 text-left">Transaction ID</th>
                <th className="border px-2 py-1">Date</th>
                <th className="border px-2 py-1">Mode</th>
                <th className="border px-2 py-1">Amount ($)</th>
                <th className="border px-2 py-1">Note</th>
                <th className="border px-2 py-1">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border px-2 py-1">TRANID11750</td>
                <td className="border px-2 py-1 text-center">
                  01/12/2026 04:58 PM
                </td>
                <td className="border px-2 py-1 text-center">Cash</td>
                <td className="border px-2 py-1 text-center">$172.50</td>
                <td className="border px-2 py-1 text-center">—</td>
                <td className="border px-2 py-1 text-center">🖨️ 🗑️</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
