# Generated by Django 5.2.8 on 2026-03-27 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('specialist', models.CharField(blank=True, max_length=255)),
                ('consultation_duration_minutes', models.IntegerField(default=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('work_shift', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('merital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socia_media_links', models.JSONField(blank=True, default=dict)),
                ('staff_id', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('local_id', models.CharField(blank=True, max_length=20)),
                ('reference_contact', models.CharField(blank=True, max_length=15)),
                ('epf_no', models.CharField(blank=True, max_length=20)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('casual_leave', models.IntegerField(default=0)),
                ('privilege_leave', models.IntegerField(default=0)),
                ('sick_leave', models.IntegerField(default=0)),
                ('maternity_leave', models.IntegerField(default=0)),
                ('paternity_leave', models.IntegerField(default=0)),
                ('fever_leave', models.IntegerField(default=0)),
                ('account_title', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_branch_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
