# Generated by Django 5.2.8 on 2025-12-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
    ]
