# Generated by Django 5.2.8 on 2026-01-23 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0002_alter_patient_gender_patientvital'),
        ('setup_module', '0004_fix_missing_vital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvital',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('charge_type', models.CharField(max_length=100)),
                ('charge_category', models.CharField(max_length=100)),
                ('charge_name', models.CharField(max_length=100)),
                ('standard_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='patient_module.patient')),
            ],
            options={
                'verbose_name': 'Patient Charge',
                'verbose_name_plural': 'Patient Charges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='patient_mod_patient_a6dbc9_idx'), models.Index(fields=['charge_type'], name='patient_mod_charge__14c192_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_date', models.DateField()),
                ('instruction', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultants_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='patient_module.patient')),
            ],
            options={
                'verbose_name': 'Patient Consultant',
                'verbose_name_plural': 'Patient Consultants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='patient_mod_patient_1758b9_idx'), models.Index(fields=['doctor'], name='patient_mod_doctor__b13e2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('assistant_consultant_1', models.CharField(blank=True, max_length=100, null=True)),
                ('assistant_consultant_2', models.CharField(blank=True, max_length=100, null=True)),
                ('ot_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('ot_assistant', models.CharField(blank=True, max_length=100, null=True)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100, null=True)),
                ('anesthetist', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='setup_module.operationsetup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patient_module.patient')),
            ],
            options={
                'verbose_name': 'Patient Operation',
                'verbose_name_plural': 'Patient Operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='patient_mod_patient_51f66f_idx'), models.Index(fields=['operation'], name='patient_mod_operati_597ac9_idx')],
            },
        ),
    ]
