# Generated by Django 5.2.8 on 2026-01-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0003_alter_patientvital_bp_alter_patientvital_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcharges',
            old_name='remark',
            new_name='charge_note',
        ),
        migrations.RemoveField(
            model_name='patientcharges',
            name='result',
        ),
        migrations.AlterField(
            model_name='patientcharges',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientcharges',
            name='charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientcharges',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
