# Generated by Django 5.2.8 on 2026-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0004_rename_remark_patientcharges_charge_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcharges',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
