# Generated by Django 5.2.4 on 2026-01-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0007_medicalcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcharges',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patient_module.medicalcase'),
        ),
    ]
