# Generated by Django 5.2.4 on 2026-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0008_patientcharges_case_patientpayment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpayment',
            name='service_type',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy'), ('Pathology', 'Pathology'), ('Radiology', 'Radiology'), ('Ambulance', 'Ambulance'), ('General', 'General')], default='General', help_text='Service module this payment is associated with', max_length=20),
        ),
    ]
