# Generated by Django 5.2.4 on 2026-02-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_module', '0004_remove_ambulancebill_bill_no'),
        ('opd_ipd_module', '0009_remove_ipdpatient_case_id_remove_opdpatient_case_id_and_more'),
        ('pathology_module', '0003_remove_pathologybill_bill_no'),
        ('patient_module', '0009_patientpayment_service_type'),
        ('pharmacy_module', '0002_pharmacybill_case'),
        ('radiology_module', '0004_remove_radiologybill_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpayment',
            name='ambulance_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ambulance_module.ambulancebill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='ipd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='opd_ipd_module.ipdpatient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='opd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='opd_ipd_module.opdpatient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='pathology_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pathology_module.pathologybill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='pharmacy_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pharmacy_module.pharmacybill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='radiology_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='radiology_module.radiologybill'),
        ),
    ]
