# Generated by Django 5.2.4 on 2026-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0010_patientpayment_ambulance_bill_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE patient_module_patient 
                DROP COLUMN IF EXISTS is_verified,
                DROP COLUMN IF EXISTS is_email_verified,
                DROP COLUMN IF EXISTS is_phone_verified,
                DROP COLUMN IF EXISTS registration_source,
                DROP COLUMN IF EXISTS uhid;
            """,
            reverse_sql="""
                ALTER TABLE patient_module_patient 
                ADD COLUMN is_verified BOOLEAN DEFAULT FALSE,
                ADD COLUMN is_email_verified BOOLEAN DEFAULT FALSE,
                ADD COLUMN is_phone_verified BOOLEAN DEFAULT FALSE;
            """
        ),
    ]
