# Generated by Django 5.2.4 on 2026-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0012_alter_patient_address_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
