import PharmacyRow from "./PharmacyRow";

export default function PharmacyTable({ bills }) {
  return (
    <div className="overflow-x-auto">
      <table className="min-w-full text-sm border-collapse">
        <thead className="bg-gray-100 border-b">
          <tr>
            <th className="px-3 py-2 text-left">Bill No</th>
            <th className="px-3 py-2 text-left">Case ID</th>
            <th className="px-3 py-2 text-left">Date</th>
            <th className="px-3 py-2 text-left">Patient Name</th>
            <th className="px-3 py-2 text-left">Generated By</th>
            <th className="px-3 py-2 text-left">Doctor Name</th>
            <th className="px-3 py-2 text-right">Amount ($)</th>
            <th className="px-3 py-2 text-right">Discount ($)</th>
            <th className="px-3 py-2 text-right">Tax ($)</th>
            <th className="px-3 py-2 text-right">Net Amount ($)</th>
            <th className="px-3 py-2 text-right">Paid Amount ($)</th>
            <th className="px-3 py-2 text-right">Refund ($)</th>
            <th className="px-3 py-2 text-right">Balance ($)</th>
            <th className="px-3 py-2 text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          {bills.map((row, i) => (
            <PharmacyRow key={i} row={row} />
          ))}
        </tbody>
      </table>
    </div>
  );
}
