# Generated by Django 5.2.8 on 2026-01-04 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_ipd_module', '0012_prescription'),
        ('pathology_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologybill',
            name='pathologytest',
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology_bills', to='opd_ipd_module.prescription'),
        ),
        migrations.AddField(
            model_name='pathologybill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pathologybill',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PathologyBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_days', models.PositiveIntegerField()),
                ('report_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pathology_module.pathologybill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology_module.pathologytest')),
            ],
        ),
    ]
