# Generated by Django 5.2.4 on 2026-02-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_module', '0002_pathologybill_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologybill',
            name='bill_no',
        ),
    ]
