# Generated by Django 5.2.8 on 2026-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_module', '0003_remove_pathologybill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologytest',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathologytest',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathologytest',
            name='test_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
