# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulance_module', '0002_initial'),
        ('opd_ipd_module', '0003_initial'),
        ('pathology_module', '0003_initial'),
        ('patient_module', '0001_initial'),
        ('pharmacy_module', '0001_initial'),
        ('radiology_module', '0001_initial'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='patientcharges',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='patientcharges',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcharges',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='patientconsultant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientconsultant',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultants_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientconsultant',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='setup_module.operationsetup'),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='ambulance_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ambulance_module.ambulancebill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patient_module.medicalcase'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='ipd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='opd_ipd_module.ipdpatient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='opd_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='opd_ipd_module.opdpatient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='pathology_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pathology_module.pathologybill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='pharmacy_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pharmacy_module.pharmacybill'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='radiology_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='radiology_module.radiologybill'),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patient_module.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patient_mod_email_d42755_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patient_mod_phone_a3ef61_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patient_mod_is_acti_5adcec_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcharges',
            index=models.Index(fields=['patient'], name='patient_mod_patient_a6dbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcharges',
            index=models.Index(fields=['charge_type'], name='patient_mod_charge__14c192_idx'),
        ),
        migrations.AddIndex(
            model_name='patientconsultant',
            index=models.Index(fields=['patient'], name='patient_mod_patient_1758b9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientconsultant',
            index=models.Index(fields=['doctor'], name='patient_mod_doctor__b13e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientoperation',
            index=models.Index(fields=['patient'], name='patient_mod_patient_51f66f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientoperation',
            index=models.Index(fields=['operation'], name='patient_mod_operati_597ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientpayment',
            index=models.Index(fields=['patient'], name='patient_mod_patient_c1d988_idx'),
        ),
        migrations.AddIndex(
            model_name='patientpayment',
            index=models.Index(fields=['payment_mode'], name='patient_mod_payment_c9b6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['patient'], name='patient_mod_patient_23aca6_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['vital_date'], name='patient_mod_vital_d_0b2d82_idx'),
        ),
    ]
