import BirthRecordRow from "./BirthRecordRow";

export default function BirthRecordTable({ data ,onView, onEdit, onDelete }) {
  return (
    <div className="overflow-x-auto">
      <table className="min-w-full border text-left bg-white">
        <thead className="bg-gray-100 text-sm">
          <tr>
            <th className="px-3 py-2">Reference No</th>
            <th className="px-3 py-2">Case ID</th>
            <th className="px-3 py-2">Generated By</th>
            <th className="px-3 py-2">Child Name</th>
            <th className="px-3 py-2">Gender</th>
            <th className="px-3 py-2">Birth Date</th>
            <th className="px-3 py-2">Mother Name</th>
            <th className="px-3 py-2">Father Name</th>
            <th className="px-3 py-2">Report</th>
          </tr>
        </thead>
        <tbody>
          {data.map((item, i) => (
            <BirthRecordRow key={i} item={item} onView={onView} onEdit={onEdit} onDelete={onDelete} />
          ))}
        </tbody>
      </table>
    </div>
  );
}
