# Generated by Django 5.2.8 on 2026-03-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd_ipd_module', '0003_initial'),
        ('patient_module', '0002_initial'),
        ('radiology_module', '0001_initial'),
        ('setup_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologybill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologybill',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologybill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_bills', to='patient_module.patient'),
        ),
        migrations.AddField(
            model_name='radiologybill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_bills', to='opd_ipd_module.prescription'),
        ),
        migrations.AddField(
            model_name='radiologybillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='radiology_module.radiologybill'),
        ),
        migrations.AddField(
            model_name='radiologycategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyparameter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologytest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='radiology_module.radiologycategory'),
        ),
        migrations.AddField(
            model_name='radiologytest',
            name='charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_tests', to='setup_module.hospitalcharges'),
        ),
        migrations.AddField(
            model_name='radiologytest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologytest',
            name='parameters',
            field=models.ManyToManyField(related_name='tests', to='radiology_module.radiologyparameter'),
        ),
        migrations.AddField(
            model_name='radiologybillitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radiology_module.radiologytest'),
        ),
        migrations.AlterUniqueTogether(
            name='radiologyparameter',
            unique_together={('parameter_name', 'unit')},
        ),
    ]
